"""PCC Kernel IR package.

This package is the kernel-only IR boundary for the ``K-P0-*`` cluster. See
``docs/design/pcc-kernel-ir.md`` for the pipeline and the hard claim boundary.

Hard claim boundary (never weakened):
  * NEVER whole-Python-on-GPU — only an explicitly-marked, statically-constrained
    kernel subset crosses the device frontier.
  * NEVER GC-managed objects in device IR — the kernel IR sees buffer handles +
    metadata, never a PyObject*.
  * LLVM is ORACLE, not OWNER — ``--backend=self`` never silently falls back.
  * Default kernel-IR helpers stay metadata/golden-only unless an explicit
    artifact-producing API is used. Artifact production still does not imply a
    GPU launch or whole-program GPU execution.

Every module here imports standalone; importing this package does NOT touch
``pcc/__init__.py``.
"""

from __future__ import annotations

from pcc.kernel_ir.ir import (
    BufferParam,
    KernelFunc,
    KernelIRError,
    LocalBuffer,
    KernelModule,
    KernelOp,
    Layout,
    MemoryScope,
    ScalarParam,
    ScalarType,
    dump_kernel,
    validate_kernel,
)
from pcc.kernel_ir.target_split import (
    DeviceTarget,
    HostBackend,
    TargetMachine,
    TargetSplitError,
    resolve,
)
from pcc.kernel_ir.hmm_fence import (
    HmmFenceError,
    PccBufferHandle,
    PccDeferredFreeQueue,
    PccFenceToken,
    PccPackedArgs,
)
from pcc.kernel_ir.ds4_gpu_mapping import (
    DS4_GPU_LIFETIME_API_MAPPING,
    Ds4GpuApiMapping,
    Ds4GpuMappingError,
    Ds4GpuMappingReport,
    Ds4ToPccLifetimeAdapter,
    PccTensorMemory,
    PccTensorReadbackWindow,
    PccTensorSlice,
    PccTensorSliceState,
    extract_ds4_gpu_lifetime_apis,
    validate_ds4_gpu_lifetime_mapping,
)
from pcc.kernel_ir.ds4_primitive import (
    DS4_COPY_REFERENCE_COMMIT,
    DS4_COPY_REFERENCE_PATH,
    DS4_COPY_REFERENCE_SHA256,
    DS4_COPY_REFERENCE_SYMBOL,
    PCC_DS4_COPY_ENTRY,
    Ds4CopyReference,
    Ds4PrimitiveError,
    build_ds4_f32_copy_args,
    build_ds4_f32_copy_module,
    ds4_f32_copy_cpu_oracle,
    validate_ds4_f32_copy_reference,
)
from pcc.kernel_ir.tirx_adapter import (
    PLAIN_TIR_FREEZE_MARKER,
    TirxAdapterError,
    lower_to_plain_tir,
)
from pcc.kernel_ir.tilelang_compat import (
    Support,
    TileLangCompatError,
    classify,
    is_accepted,
)
from pcc.kernel_ir.tilelang_import import (
    TILELANG_WGMMA_LAYOUT_REFERENCE_COMMIT,
    TILELANG_WGMMA_LAYOUT_REFERENCE_PATH,
    TILELANG_WGMMA_LAYOUT_REFERENCE_SHA256,
    TileLangImportError,
    import_tilelang_file,
    import_tilelang_source,
)
from pcc.kernel_ir.tilelang_dynamic_shape import (
    DYNAMIC_SHAPE_CONTRACT_VERSION,
    UINT32_MAX,
    UINT64_MAX,
    TileLangDynamicShapeContract,
    TileLangDynamicShapeError,
    TileLangShapeSpecialization,
)
from pcc.kernel_ir.cpu_reference import (
    CpuReferenceResult,
    KernelCpuReferenceError,
    execute_static_fill_reference,
    execute_static_indexed_reference,
    execute_sparse_tiled_gemm_sp_reference,
    execute_scalar_tiled_gemm_reference,
)
from pcc.kernel_ir.metal_buffer import (
    MetalNativeBufferAllocation,
    MetalNativeBufferAllocationSet,
    MetalNativeBufferBinding,
    MetalNativeBufferBindingError,
    MetalNativeBufferBindingSet,
    MetalNativeBufferRuntimeArtifacts,
    MetalNativeBufferDataTransferResult,
    MetalNativeBufferRuntimeError,
    MetalNativeBufferRuntimeSmokeResult,
    STATUS_NATIVE_BUFFER_ALLOCATIONS_READY,
    STATUS_NATIVE_BUFFER_BINDINGS_READY,
    STATUS_NATIVE_BUFFER_DATA_ROUNDTRIP_VALIDATED,
    STATUS_NATIVE_BUFFER_DATA_TRANSFER_VALIDATED,
    STATUS_NATIVE_BUFFER_RUNTIME_CALL_VALIDATED,
    STATUS_NATIVE_BUFFER_RUNTIME_LIBRARY_PRODUCED,
    STATUS_NATIVE_BUFFER_RUNTIME_LOAD_VALIDATED,
    STATUS_NATIVE_BUFFER_RUNTIME_OBJECT_PRODUCED,
    STATUS_NATIVE_BUFFER_RUNTIME_SOURCE_ONLY,
    allocate_metal_native_buffers_for_plan,
    build_metal_native_buffer_runtime_artifacts,
    build_metal_native_buffer_binding_set,
    emit_metal_native_buffer_runtime_source,
    read_metal_native_buffer,
    roundtrip_metal_native_buffer_bytes,
    smoke_metal_native_buffer_runtime,
    write_metal_native_buffer,
)
from pcc.kernel_ir.metal_invoke import (
    MetalBridgeInvocationError,
    MetalBridgeInvocationResult,
    STATUS_BRIDGE_INVOCATION_ABI_VALIDATED,
    STATUS_BRIDGE_INVOCATION_FAILED,
    STATUS_BRIDGE_INVOKED,
    invoke_metal_bridge_packet,
)
from pcc.kernel_ir.metal_source_runtime import (
    MetalSourceRuntimeBridgeArtifacts,
    MetalSourceRuntimeError,
    MetalSourceRuntimeInvocationResult,
    MetalSourceRuntimePackageResult,
    STATUS_SOURCE_RUNTIME_BRIDGE_LIBRARY_PRODUCED,
    STATUS_SOURCE_RUNTIME_BRIDGE_LOAD_VALIDATED,
    STATUS_SOURCE_RUNTIME_BRIDGE_OBJECT_PRODUCED,
    STATUS_SOURCE_RUNTIME_BRIDGE_SOURCE_ONLY,
    STATUS_SOURCE_RUNTIME_INVOCATION_ABI_VALIDATED,
    STATUS_SOURCE_RUNTIME_INVOCATION_FAILED,
    STATUS_SOURCE_RUNTIME_INVOKED,
    STATUS_SOURCE_RUNTIME_PACKAGE_ABI_VALIDATED,
    STATUS_SOURCE_RUNTIME_PACKAGE_EXECUTED,
    STATUS_SOURCE_RUNTIME_PACKAGE_FAILED,
    build_metal_source_runtime_bridge_artifacts,
    emit_metal_source_runtime_bridge_source,
    invoke_metal_source_runtime_bridge,
    metal_source_runtime_package_manifest_dict,
    metal_source_runtime_bridge_symbol,
    run_metal_source_runtime_package,
    verify_metal_source_runtime_package_manifest,
    write_metal_source_runtime_package_manifest,
)
from pcc.kernel_ir.metal_metallib_runtime import (
    MetalMetallibRuntimeError,
    MetalMetallibRuntimePackageResult,
    STATUS_METALLIB_RUNTIME_PACKAGE_ABI_VALIDATED,
    STATUS_METALLIB_RUNTIME_PACKAGE_EXECUTED,
    STATUS_METALLIB_RUNTIME_PACKAGE_FAILED,
    run_metal_metallib_runtime_package,
)
from pcc.kernel_ir.gpu_claims import (
    GpuClaimError,
    GpuClaimEvidence,
    GpuClaimLevel,
    classify_metal_source_runtime_package_result,
    require_device_result_or_skip,
)
from pcc.kernel_ir.gpu_owner_backend import (
    GPU_BACKEND_PCC_METAL,
    GPU_BACKEND_TVM_TILELANG,
    PCC_METAL_DRIVER_IDENTITY,
    PCC_METAL_SCALAR_PIPELINE,
    PCC_METAL_SIMDGROUP_GEMM_PIPELINE,
    GpuBackendCapabilities,
    GpuBackendDriver,
    GpuBackendError,
    GpuBackendUnavailable,
    GpuOwnerExecutionResult,
    GpuOwnerManifest,
    PccMetalCompileArtifacts,
    PccMetalGpuBackendDriver,
    PccMetalPackage,
    PccMetalValidation,
    TvmTilelangCompileArtifacts,
    TvmTilelangGpuBackendDriver,
    TvmTilelangPackage,
    TvmTilelangValidation,
    get_gpu_backend_driver,
    pcc_metal_owner_identity_fields,
    tvm_tilelang_owner_identity_fields,
    validate_gpu_owner_identity,
)
from pcc.kernel_ir.metal_tensor import (
    MetalMatrixReadbackResult,
    MetalMatrixTransfer,
    MetalMatrixTransferSet,
    MetalTensorTransferError,
    STATUS_METAL_MATRIX_BUFFERS_READY,
    STATUS_METAL_MATRIX_READBACK_VALIDATED,
    pack_matrix_to_metal_bytes,
    read_metal_launch_matrix,
    unpack_matrix_from_metal_bytes,
    write_metal_launch_matrices,
)
from pcc.kernel_ir.metal_dlpack import (
    DLDataType,
    DLDevice,
    DLManagedTensor,
    DLManagedTensorDeleter,
    DLTensor,
    DLPACK_CAPSULE_NAME,
    ImportedMetalDlpackCapsule,
    ImportedMetalDlpackTensor,
    MetalDlpackCapsuleExport,
    MetalDlpackManagedTensor,
    MetalDlpackOwnershipError,
    MetalDlpackProtocolExport,
    MetalDlpackReclaimResult,
    MetalDlpackReleaseResult,
    MetalDlpackTensorDescriptor,
    MetalDlpackTensorOwner,
    STATUS_METAL_DLPACK_ALIAS_DROPPED,
    STATUS_METAL_DLPACK_CAPSULE_EXPORTED,
    STATUS_METAL_DLPACK_CAPSULE_IMPORTED,
    STATUS_METAL_DLPACK_NATIVE_RELEASED,
    STATUS_METAL_DLPACK_RECLAIM_PENDING,
    STATUS_METAL_DLPACK_RELEASE_DEFERRED,
    STATUS_METAL_DLPACK_TENSOR_EXPORTED,
    STATUS_METAL_DLPACK_TENSOR_IMPORTED,
    USED_DLPACK_CAPSULE_NAME,
    export_metal_dlpack_protocol,
    export_metal_dlpack_py_capsule,
    import_metal_dlpack_tensor,
    import_metal_dlpack_py_capsule,
    pycapsule_name,
)
from pcc.kernel_ir.metal_verify import (
    MetalCpuOracleCompareError,
    MetalCpuOracleComparisonResult,
    STATUS_METAL_CPU_ORACLE_MATCH,
    verify_metal_launch_output_against_cpu_reference,
)
from pcc.kernel_ir.metal_package import (
    MetalBridgeInvocationPacket,
    MetalKernelPackage,
    MetalPackageError,
    STATUS_BRIDGE_INVOCATION_PACKET_READY,
    STATUS_BRIDGE_LIBRARY_NOT_REQUESTED,
    STATUS_BRIDGE_LIBRARY_PRODUCED,
    STATUS_BRIDGE_LIBRARY_LOAD_NOT_REQUESTED,
    STATUS_BRIDGE_LIBRARY_LOAD_VALIDATED,
    STATUS_BRIDGE_INVOCATION_PACKET_NOT_READY,
    STATUS_SKIPPED_WITH_REASON as STATUS_PACKAGE_SKIPPED_WITH_REASON,
    build_metal_bridge_invocation_packet,
    build_metal_kernel_package,
    metal_kernel_package_manifest_dict,
    verify_metal_kernel_package_manifest,
    write_metal_kernel_package_manifest,
)
from pcc.kernel_ir.metal_finalize import (
    STATUS_ARTIFACTS_PRODUCED,
    STATUS_DESCRIPTOR_ONLY,
    STATUS_SOURCE_ONLY,
    STATUS_SKIPPED_WITH_REASON,
    MetalFinalizeError,
    emit_metal_simdgroup_gemm_source,
    emit_metal_source,
    finalize_metal,
)
from pcc.kernel_ir.metal_launch import (
    STATUS_BRIDGE_OBJECT_PRODUCED,
    STATUS_BRIDGE_SOURCE_ONLY,
    STATUS_PLAN_ONLY,
    MetalExecutorBridgeArtifacts,
    MetalExecutorBridgeSource,
    MetalDispatchShape,
    MetalLaunchError,
    MetalLaunchPlan,
    MetalLaunchResult,
    MetalRuntimeArg,
    build_metal_executor_bridge_artifacts,
    emit_metal_executor_bridge_source,
    metal_executor_bridge_symbol,
    plan_metal_launch,
    prepare_metal_launch,
    write_metal_executor_bridge_source,
)
from pcc.kernel_ir.host_device_split import (
    DeviceLocalBinding,
    HostDeviceSplitError,
    HostDeviceSplitProof,
    KernelArgBinding,
    KernelLaunchBoundary,
    TirxMetalHostDeviceResult,
    build_host_launch_boundaries,
    prove_tirx_metal_host_device_split,
)
from pcc.kernel_ir.tvm_oracle import (
    TvmOracleError,
    project_to_tir_shape,
)

__all__ = [
    # ir
    "KernelIRError",
    "ScalarType",
    "MemoryScope",
    "Layout",
    "ScalarParam",
    "BufferParam",
    "KernelOp",
    "KernelFunc",
    "LocalBuffer",
    "KernelModule",
    "validate_kernel",
    "dump_kernel",
    # target_split
    "TargetSplitError",
    "HostBackend",
    "DeviceTarget",
    "TargetMachine",
    "resolve",
    # hmm_fence
    "HmmFenceError",
    "PccBufferHandle",
    "PccFenceToken",
    "PccPackedArgs",
    "PccDeferredFreeQueue",
    # ds4_gpu_mapping
    "DS4_GPU_LIFETIME_API_MAPPING",
    "Ds4GpuApiMapping",
    "Ds4GpuMappingError",
    "Ds4GpuMappingReport",
    "Ds4ToPccLifetimeAdapter",
    "PccTensorMemory",
    "PccTensorReadbackWindow",
    "PccTensorSlice",
    "PccTensorSliceState",
    "extract_ds4_gpu_lifetime_apis",
    "validate_ds4_gpu_lifetime_mapping",
    # ds4_primitive
    "DS4_COPY_REFERENCE_COMMIT",
    "DS4_COPY_REFERENCE_PATH",
    "DS4_COPY_REFERENCE_SHA256",
    "DS4_COPY_REFERENCE_SYMBOL",
    "PCC_DS4_COPY_ENTRY",
    "Ds4CopyReference",
    "Ds4PrimitiveError",
    "build_ds4_f32_copy_args",
    "build_ds4_f32_copy_module",
    "ds4_f32_copy_cpu_oracle",
    "validate_ds4_f32_copy_reference",
    # tirx_adapter
    "PLAIN_TIR_FREEZE_MARKER",
    "TirxAdapterError",
    "lower_to_plain_tir",
    # tilelang_compat
    "Support",
    "TileLangCompatError",
    "classify",
    "is_accepted",
    # tilelang_import
    "TileLangImportError",
    "TILELANG_WGMMA_LAYOUT_REFERENCE_COMMIT",
    "TILELANG_WGMMA_LAYOUT_REFERENCE_PATH",
    "TILELANG_WGMMA_LAYOUT_REFERENCE_SHA256",
    "import_tilelang_file",
    "import_tilelang_source",
    # tilelang_dynamic_shape
    "DYNAMIC_SHAPE_CONTRACT_VERSION",
    "UINT32_MAX",
    "UINT64_MAX",
    "TileLangDynamicShapeContract",
    "TileLangDynamicShapeError",
    "TileLangShapeSpecialization",
    # cpu_reference
    "CpuReferenceResult",
    "KernelCpuReferenceError",
    "execute_static_fill_reference",
    "execute_static_indexed_reference",
    "execute_sparse_tiled_gemm_sp_reference",
    "execute_scalar_tiled_gemm_reference",
    # metal_buffer
    "MetalNativeBufferAllocation",
    "MetalNativeBufferAllocationSet",
    "MetalNativeBufferBinding",
    "MetalNativeBufferBindingError",
    "MetalNativeBufferBindingSet",
    "MetalNativeBufferRuntimeArtifacts",
    "MetalNativeBufferDataTransferResult",
    "MetalNativeBufferRuntimeError",
    "MetalNativeBufferRuntimeSmokeResult",
    "STATUS_NATIVE_BUFFER_ALLOCATIONS_READY",
    "STATUS_NATIVE_BUFFER_BINDINGS_READY",
    "STATUS_NATIVE_BUFFER_DATA_ROUNDTRIP_VALIDATED",
    "STATUS_NATIVE_BUFFER_DATA_TRANSFER_VALIDATED",
    "STATUS_NATIVE_BUFFER_RUNTIME_CALL_VALIDATED",
    "STATUS_NATIVE_BUFFER_RUNTIME_LIBRARY_PRODUCED",
    "STATUS_NATIVE_BUFFER_RUNTIME_LOAD_VALIDATED",
    "STATUS_NATIVE_BUFFER_RUNTIME_OBJECT_PRODUCED",
    "STATUS_NATIVE_BUFFER_RUNTIME_SOURCE_ONLY",
    "allocate_metal_native_buffers_for_plan",
    "build_metal_native_buffer_binding_set",
    "build_metal_native_buffer_runtime_artifacts",
    "emit_metal_native_buffer_runtime_source",
    "read_metal_native_buffer",
    "roundtrip_metal_native_buffer_bytes",
    "smoke_metal_native_buffer_runtime",
    "write_metal_native_buffer",
    # metal_invoke
    "MetalBridgeInvocationError",
    "MetalBridgeInvocationResult",
    "STATUS_BRIDGE_INVOCATION_ABI_VALIDATED",
    "STATUS_BRIDGE_INVOCATION_FAILED",
    "STATUS_BRIDGE_INVOKED",
    "invoke_metal_bridge_packet",
    # metal_source_runtime
    "MetalSourceRuntimeBridgeArtifacts",
    "MetalSourceRuntimeError",
    "MetalSourceRuntimeInvocationResult",
    "MetalSourceRuntimePackageResult",
    "STATUS_SOURCE_RUNTIME_BRIDGE_LIBRARY_PRODUCED",
    "STATUS_SOURCE_RUNTIME_BRIDGE_LOAD_VALIDATED",
    "STATUS_SOURCE_RUNTIME_BRIDGE_OBJECT_PRODUCED",
    "STATUS_SOURCE_RUNTIME_BRIDGE_SOURCE_ONLY",
    "STATUS_SOURCE_RUNTIME_INVOCATION_ABI_VALIDATED",
    "STATUS_SOURCE_RUNTIME_INVOCATION_FAILED",
    "STATUS_SOURCE_RUNTIME_INVOKED",
    "STATUS_SOURCE_RUNTIME_PACKAGE_ABI_VALIDATED",
    "STATUS_SOURCE_RUNTIME_PACKAGE_EXECUTED",
    "STATUS_SOURCE_RUNTIME_PACKAGE_FAILED",
    "build_metal_source_runtime_bridge_artifacts",
    "emit_metal_source_runtime_bridge_source",
    "invoke_metal_source_runtime_bridge",
    "metal_source_runtime_package_manifest_dict",
    "metal_source_runtime_bridge_symbol",
    "run_metal_source_runtime_package",
    "verify_metal_source_runtime_package_manifest",
    "write_metal_source_runtime_package_manifest",
    # metal_metallib_runtime
    "MetalMetallibRuntimeError",
    "MetalMetallibRuntimePackageResult",
    "STATUS_METALLIB_RUNTIME_PACKAGE_ABI_VALIDATED",
    "STATUS_METALLIB_RUNTIME_PACKAGE_EXECUTED",
    "STATUS_METALLIB_RUNTIME_PACKAGE_FAILED",
    "run_metal_metallib_runtime_package",
    # gpu_claims
    "GpuClaimError",
    "GpuClaimEvidence",
    "GpuClaimLevel",
    "classify_metal_source_runtime_package_result",
    "require_device_result_or_skip",
    # gpu_owner_backend
    "GPU_BACKEND_PCC_METAL",
    "GPU_BACKEND_TVM_TILELANG",
    "PCC_METAL_DRIVER_IDENTITY",
    "PCC_METAL_SCALAR_PIPELINE",
    "PCC_METAL_SIMDGROUP_GEMM_PIPELINE",
    "GpuBackendCapabilities",
    "GpuBackendDriver",
    "GpuBackendError",
    "GpuBackendUnavailable",
    "GpuOwnerExecutionResult",
    "GpuOwnerManifest",
    "PccMetalCompileArtifacts",
    "PccMetalGpuBackendDriver",
    "PccMetalPackage",
    "PccMetalValidation",
    "TvmTilelangCompileArtifacts",
    "TvmTilelangGpuBackendDriver",
    "TvmTilelangPackage",
    "TvmTilelangValidation",
    "get_gpu_backend_driver",
    "pcc_metal_owner_identity_fields",
    "tvm_tilelang_owner_identity_fields",
    "validate_gpu_owner_identity",
    # metal_tensor
    "MetalMatrixReadbackResult",
    "MetalMatrixTransfer",
    "MetalMatrixTransferSet",
    "MetalTensorTransferError",
    "STATUS_METAL_MATRIX_BUFFERS_READY",
    "STATUS_METAL_MATRIX_READBACK_VALIDATED",
    "pack_matrix_to_metal_bytes",
    "read_metal_launch_matrix",
    "unpack_matrix_from_metal_bytes",
    "write_metal_launch_matrices",
    # metal_dlpack
    "DLPACK_CAPSULE_NAME",
    "ImportedMetalDlpackCapsule",
    "ImportedMetalDlpackTensor",
    "MetalDlpackCapsuleExport",
    "MetalDlpackManagedTensor",
    "MetalDlpackOwnershipError",
    "MetalDlpackProtocolExport",
    "MetalDlpackReclaimResult",
    "MetalDlpackReleaseResult",
    "MetalDlpackTensorDescriptor",
    "MetalDlpackTensorOwner",
    "STATUS_METAL_DLPACK_ALIAS_DROPPED",
    "STATUS_METAL_DLPACK_CAPSULE_EXPORTED",
    "STATUS_METAL_DLPACK_CAPSULE_IMPORTED",
    "STATUS_METAL_DLPACK_NATIVE_RELEASED",
    "STATUS_METAL_DLPACK_RECLAIM_PENDING",
    "STATUS_METAL_DLPACK_RELEASE_DEFERRED",
    "STATUS_METAL_DLPACK_TENSOR_EXPORTED",
    "STATUS_METAL_DLPACK_TENSOR_IMPORTED",
    "USED_DLPACK_CAPSULE_NAME",
    "export_metal_dlpack_protocol",
    "export_metal_dlpack_py_capsule",
    "import_metal_dlpack_tensor",
    "import_metal_dlpack_py_capsule",
    "pycapsule_name",
    # metal_verify
    "MetalCpuOracleCompareError",
    "MetalCpuOracleComparisonResult",
    "STATUS_METAL_CPU_ORACLE_MATCH",
    "verify_metal_launch_output_against_cpu_reference",
    # metal_package
    "MetalBridgeInvocationPacket",
    "MetalKernelPackage",
    "MetalPackageError",
    "STATUS_BRIDGE_INVOCATION_PACKET_READY",
    "STATUS_BRIDGE_LIBRARY_NOT_REQUESTED",
    "STATUS_BRIDGE_LIBRARY_PRODUCED",
    "STATUS_BRIDGE_LIBRARY_LOAD_NOT_REQUESTED",
    "STATUS_BRIDGE_LIBRARY_LOAD_VALIDATED",
    "STATUS_BRIDGE_INVOCATION_PACKET_NOT_READY",
    "STATUS_PACKAGE_SKIPPED_WITH_REASON",
    "build_metal_bridge_invocation_packet",
    "build_metal_kernel_package",
    "metal_kernel_package_manifest_dict",
    "verify_metal_kernel_package_manifest",
    "write_metal_kernel_package_manifest",
    # metal_finalize
    "STATUS_ARTIFACTS_PRODUCED",
    "STATUS_DESCRIPTOR_ONLY",
    "STATUS_SOURCE_ONLY",
    "STATUS_SKIPPED_WITH_REASON",
    "MetalFinalizeError",
    "emit_metal_simdgroup_gemm_source",
    "emit_metal_source",
    "finalize_metal",
    # metal_launch
    "STATUS_PLAN_ONLY",
    "STATUS_BRIDGE_SOURCE_ONLY",
    "STATUS_BRIDGE_OBJECT_PRODUCED",
    "MetalLaunchError",
    "MetalDispatchShape",
    "MetalRuntimeArg",
    "MetalLaunchPlan",
    "MetalLaunchResult",
    "MetalExecutorBridgeSource",
    "MetalExecutorBridgeArtifacts",
    "build_metal_executor_bridge_artifacts",
    "emit_metal_executor_bridge_source",
    "metal_executor_bridge_symbol",
    "plan_metal_launch",
    "prepare_metal_launch",
    "write_metal_executor_bridge_source",
    # tvm_oracle
    "TvmOracleError",
    "project_to_tir_shape",
    # host_device_split
    "HostDeviceSplitError",
    "DeviceLocalBinding",
    "KernelArgBinding",
    "KernelLaunchBoundary",
    "HostDeviceSplitProof",
    "TirxMetalHostDeviceResult",
    "build_host_launch_boundaries",
    "prove_tirx_metal_host_device_split",
]
