from __future__ import annotations

from contextlib import contextmanager
import hashlib
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
import json
import os
import subprocess
import sys
import tarfile
import threading
import zipfile
from pathlib import Path

from pcc1_gate import repo_root

import pytest

from pcc1_gate import find_current_pcc1, skip_or_fail_no_current_pcc1

from pcc.package.install import _build_requirement_tool_wrappers, install_package
from pcc.package.metadata import (
    current_platform_tag,
    inspect_artifact,
    pcc_native_wheel_tag,
)
from pcc.package.wheel_repo import repository_report

REPO = repo_root()


def _find_current_pcc1() -> Path | None:
    return find_current_pcc1(REPO)


def _write_demo_project(root: Path) -> Path:
    root.mkdir()
    pkg = root / "demo_pkg"
    pkg.mkdir()
    (pkg / "__init__.py").write_text("VALUE = 1\n", encoding="utf-8")
    (pkg / "core.py").write_text(
        "def answer() -> int:\n" "    return 42\n",
        encoding="utf-8",
    )
    (root / "demo_pkg.pyx").write_text("cdef int value\n", encoding="utf-8")
    (root / "demo_pkg.c").write_text(
        "/* Generated by Cython */\nint demo(void) { return 1; }\n",
        encoding="utf-8",
    )
    (root / "solver.f90").write_text("subroutine solver()\nend\n", encoding="utf-8")
    (root / "blas_probe.c").write_text(
        "int blas_probe(void) { return 0; }\n", encoding="utf-8"
    )
    (root / "lapack_probe.c").write_text(
        "int lapack_probe(void) { return 0; }\n", encoding="utf-8"
    )
    (root / "meson.build").write_text("project('demo_pkg', 'c')\n", encoding="utf-8")
    (root / "pyproject.toml").write_text(
        "[project]\nname = 'demo_pkg'\nversion = '0.1'\n"
        "[build-system]\n"
        "requires = ['meson-python', 'cython']\n"
        "build-backend = 'mesonpy'\n",
        encoding="utf-8",
    )
    (root / "compile_commands.json").write_text(
        json.dumps(
            [
                {"file": str(root / "demo_pkg.c"), "command": "cc -c demo_pkg.c"},
                {"file": str(root / "solver.f90"), "command": "gfortran -c solver.f90"},
            ]
        ),
        encoding="utf-8",
    )
    return root


def _write_demo_meson_build_overlay(project: Path) -> None:
    build_pkg = project / "build" / "pcc-package" / "meson-build" / "demo_pkg"
    build_pkg.mkdir(parents=True)
    (build_pkg / "__init__.py").write_text("VALUE = 2\n", encoding="utf-8")
    (build_pkg / "generated.py").write_text("BUILD_VALUE = 99\n", encoding="utf-8")
    (build_pkg / "_native.so").write_text("pcc-native placeholder\n", encoding="utf-8")


def _write_fake_vendored_meson(project: Path) -> None:
    meson_py = project / "vendored-meson" / "meson" / "meson.py"
    meson_py.parent.mkdir(parents=True)
    meson_py.write_text(
        "from pathlib import Path\n"
        "import sys\n"
        "builddir = Path(sys.argv[2])\n"
        "builddir.mkdir(parents=True, exist_ok=True)\n"
        '(builddir / \'build.ninja\').write_text("""\n'
        "rule gen\n"
        "  command = /bin/sh -c \\\"mkdir -p demo_pkg && printf 'VALUE = 2\\\\n' > demo_pkg/__init__.py && printf 'BUILD_VALUE = 99\\\\n' > demo_pkg/generated.py\\\"\n"
        "build demo_pkg/generated.py: gen\n"
        "default demo_pkg/generated.py\n"
        '""", encoding=\'utf-8\')\n',
        encoding="utf-8",
    )


def _write_demo_wheel(
    path: Path,
    *,
    requires: tuple[str, ...] = (),
    native_libpython: bool = False,
    cpython_extension_abi: bool = False,
) -> Path:
    metadata = "Name: demo-pkg\n"
    for dep in requires:
        metadata += f"Requires-Dist: {dep}\n"
    with zipfile.ZipFile(path, "w") as zf:
        zf.writestr("demo_pkg/__init__.py", "VALUE = 1\n")
        zf.writestr(
            "demo_pkg/core.py",
            "def answer() -> int:\n" "    return 42\n",
        )
        if native_libpython:
            zf.writestr("demo_pkg/bad.so", "/usr/local/lib/libpython3.13.dylib\n")
        if cpython_extension_abi:
            zf.writestr("demo_pkg/_demo.cpython-314-darwin.so", "libpcc_runtime\n")
        zf.writestr("demo_pkg-0.1.dist-info/METADATA", metadata)
    return path


def _write_helper_wheel(path: Path) -> Path:
    with zipfile.ZipFile(path, "w") as zf:
        zf.writestr("helper_pkg/__init__.py", "VALUE = 2\n")
        zf.writestr("helper_pkg/core.py", "def helper() -> int:\n    return 7\n")
        zf.writestr("helper_pkg-0.1.dist-info/METADATA", "Name: helper-pkg\n")
    return path


@contextmanager
def _serve_directory(root: Path):
    class Handler(SimpleHTTPRequestHandler):
        def __init__(self, *args, **kwargs):
            super().__init__(*args, directory=str(root), **kwargs)

        def log_message(self, format, *args):  # noqa: A002
            return

    server = ThreadingHTTPServer(("127.0.0.1", 0), Handler)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    try:
        host, port = server.server_address
        yield f"http://{host}:{port}"
    finally:
        server.shutdown()
        server.server_close()
        thread.join(timeout=5)


def _write_simple_index(root: Path, wheel: Path) -> str:
    simple = root / "simple" / "demo-pkg"
    simple.mkdir(parents=True, exist_ok=True)
    digest = hashlib.sha256(wheel.read_bytes()).hexdigest()
    href = "/packages/" + wheel.name + "#sha256=" + digest
    (simple / "index.html").write_text(
        f'<html><body><a href="{href}">{wheel.name}</a></body></html>\n',
        encoding="utf-8",
    )
    return "/simple"


def test_artifact_metadata_covers_l9_l10_build_surfaces(tmp_path):
    project = _write_demo_project(tmp_path / "demo_pkg-0.1")
    meta = inspect_artifact("demo_pkg", project).as_dict()
    assert meta["source_kind"] == "local_source"
    assert meta["pyproject_build_backend"] == "mesonpy"
    assert meta["meson_build"] is True
    assert meta["compile_commands"]["entries"] == 2
    assert meta["generated_c_policy"] == "consume_generated_c"
    assert meta["requires_cython_regeneration"] is False
    assert meta["generated_c_artifacts"] == ["demo_pkg.c"]
    assert meta["cython_sources"] == ["demo_pkg.pyx"]
    assert meta["fortran_sources"] == ["solver.f90"]
    assert "blas_probe.c" in meta["blas_indicators"]
    assert "lapack_probe.c" in meta["lapack_indicators"]
    assert meta["pcc_native_wheel_tag"] == pcc_native_wheel_tag()


def test_source_install_prefers_distribution_package_and_scans_build_overlay(
    tmp_path,
):
    project = tmp_path / "demo_pkg-0.1"
    (project / "demo_pkg").mkdir(parents=True)
    (project / "pyproject.toml").write_text(
        '[project]\nname="demo-pkg"\nversion="0.1"\n', encoding="utf-8"
    )
    (project / "demo_pkg" / "__init__.py").write_text("VALUE = 1\n", encoding="utf-8")
    (project / "benchmarks").mkdir()
    (project / "benchmarks" / "__init__.py").write_text("\n", encoding="utf-8")
    built = project / "build" / "pcc-package" / "meson-build" / "demo_pkg"
    built.mkdir(parents=True)
    (built / "_native.cpython-314-darwin.so").write_text(
        "libpcc_runtime\n", encoding="utf-8"
    )

    result = install_package(
        str(project),
        target_dir=tmp_path / "site",
        cache_dir=tmp_path / "cache",
        abi="pcc-native",
    )

    assert result["ok"] is False
    assert result["installed_path"] == str(tmp_path / "site" / "demo_pkg")
    assert result["linkage"]["uses_cpython_extension_abi"] is True
    assert not (tmp_path / "site" / "benchmarks").exists()


def test_artifact_metadata_excludes_non_build_tree_surfaces(tmp_path):
    project = tmp_path / "demo_pkg-0.1"
    project.mkdir()
    (project / "demo_pkg").mkdir()
    (project / "demo_pkg" / "__init__.py").write_text("VALUE = 1\n", encoding="utf-8")
    (project / "demo_pkg" / "_native.pyx").write_text(
        "cdef int value\n", encoding="utf-8"
    )
    (project / "doc" / "source").mkdir(parents=True)
    (project / "doc" / "source" / "example.f90").write_text(
        "subroutine demo()\nend\n", encoding="utf-8"
    )
    (project / "tests" / "examples").mkdir(parents=True)
    (project / "tests" / "examples" / "checks.pyx").write_text(
        "cdef int ignored\n", encoding="utf-8"
    )
    (project / "vendored-meson" / "meson" / "test cases" / "cython").mkdir(parents=True)
    (
        project / "vendored-meson" / "meson" / "test cases" / "cython" / "storer.pyx"
    ).write_text(
        "cdef int ignored\n",
        encoding="utf-8",
    )
    (
        project / "vendored-meson" / "meson" / "test cases" / "cython" / "storer.c"
    ).write_text(
        "/* Generated by Cython */\n",
        encoding="utf-8",
    )
    (project / ".github" / "workflows").mkdir(parents=True)
    (project / ".github" / "workflows" / "linux_blas.yml").write_text(
        "blas\n", encoding="utf-8"
    )

    meta = inspect_artifact("demo_pkg", project).as_dict()
    assert meta["cython_sources"] == ["demo_pkg/_native.pyx"]
    assert meta["fortran_sources"] == []
    assert meta["generated_c_artifacts"] == []
    assert meta["generated_c_policy"] == "requires_cython_regeneration"
    assert meta["requires_cython_regeneration"] is True
    assert meta["blas_indicators"] == []


def test_artifact_metadata_reads_meson_native_library_fallbacks(tmp_path):
    project = tmp_path / "demo_pkg-0.1"
    project.mkdir()
    (project / "demo_pkg").mkdir()
    (project / "demo_pkg" / "__init__.py").write_text("VALUE = 1\n", encoding="utf-8")
    (project / "meson.build").write_text("project('demo_pkg', 'c')\n", encoding="utf-8")
    (project / "meson.options").write_text(
        "option('allow-noblas', type: 'boolean', value: true,\n"
        "        description: 'allow internal fallback routines')\n",
        encoding="utf-8",
    )
    (project / "demo_pkg" / "blas_probe.c").write_text(
        "int blas_probe(void) { return 0; }\n", encoding="utf-8"
    )
    (project / "demo_pkg" / "lapack_probe.c").write_text(
        "int lapack_probe(void) { return 0; }\n", encoding="utf-8"
    )

    meta = inspect_artifact("demo_pkg", project).as_dict()
    assert meta["native_library_fallbacks"] == ["blas", "lapack"]
    assert "demo_pkg/blas_probe.c" in meta["blas_indicators"]
    assert "demo_pkg/lapack_probe.c" in meta["lapack_indicators"]


def test_numpy_local_source_metadata_filters_non_build_surfaces():
    numpy_root = REPO / "projects" / "numpy-2.4.4"
    if not numpy_root.exists():
        pytest.fail("local NumPy source tree is not present")

    meta = inspect_artifact("", numpy_root).as_dict()
    assert "numpy/random/_common.pyx" in meta["cython_sources"]
    assert meta["fortran_sources"] == []
    assert meta["generated_c_policy"] == "requires_cython_regeneration"
    assert meta["requires_cython_regeneration"] is True
    assert meta["native_library_fallbacks"] == ["blas", "lapack"]
    ignored_prefixes = (
        ".github/",
        "doc/",
        "numpy/_core/tests/",
        "numpy/f2py/tests/",
        "tools/",
        "vendored-meson/",
    )
    for key in (
        "cython_sources",
        "fortran_sources",
        "blas_indicators",
        "lapack_indicators",
    ):
        assert not any(str(path).startswith(ignored_prefixes) for path in meta[key])


def test_wheel_and_sdist_metadata(tmp_path):
    wheel = tmp_path / "demo_pkg-0.1-py3-none-any.whl"
    with zipfile.ZipFile(wheel, "w") as zf:
        zf.writestr("demo_pkg/__init__.py", "VALUE = 1\n")
        zf.writestr("demo_pkg-0.1.dist-info/METADATA", "Name: demo-pkg\n")
    wheel_meta = inspect_artifact("", wheel).as_dict()
    assert wheel_meta["source_kind"] == "wheel"
    assert wheel_meta["python_tag"] == "py3"
    assert wheel_meta["abi_tag"] == "none"
    assert wheel_meta["platform_tag"] == "any"

    sdist = tmp_path / "demo_pkg-0.1.tar.gz"
    src = tmp_path / "src"
    src.mkdir()
    (src / "demo_pkg.pyx").write_text("cdef int value\n", encoding="utf-8")
    with tarfile.open(sdist, "w:gz") as tf:
        tf.add(src / "demo_pkg.pyx", arcname="demo_pkg-0.1/demo_pkg.pyx")
    sdist_meta = inspect_artifact("", sdist).as_dict()
    assert sdist_meta["source_kind"] == "sdist"
    assert sdist_meta["generated_c_policy"] == "requires_cython_regeneration"


def test_local_and_cached_install_write_manifest(tmp_path):
    project = _write_demo_project(tmp_path / "demo_pkg-0.1")
    site = tmp_path / "site"
    cache = tmp_path / "cache"
    result = install_package(
        str(project),
        target_dir=site,
        cache_dir=cache,
        abi="pcc-native",
    )
    assert result["ok"] is True
    manifest_path = Path(result["manifest_path"])
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    assert manifest["abi_mode"] == "pcc-native"
    assert manifest["links_libpython"] is False
    assert manifest["no_libpython_runtime"] is True
    assert Path(manifest["installed_payload"]).exists()
    assert (site / "demo_pkg" / "__init__.py").exists()
    assert (site / "demo_pkg" / "core.py").exists()
    assert (cache / "demo_pkg" / "pcc-package.json").exists()
    assert (cache / "demo_pkg" / "__init__.py").exists()
    assert (cache / "demo_pkg" / "core.py").exists()

    cached = install_package("demo_pkg", target_dir=tmp_path / "site2", cache_dir=cache)
    assert cached["ok"] is True
    assert cached["source_path"] == str(cache / "demo_pkg")
    assert (tmp_path / "site2" / "demo_pkg" / "__init__.py").exists()
    assert (tmp_path / "site2" / "demo_pkg" / "core.py").exists()


def test_local_install_overlays_pcc_meson_build_payload(tmp_path):
    project = _write_demo_project(tmp_path / "demo_pkg-0.1")
    _write_demo_meson_build_overlay(project)

    result = install_package(
        str(project),
        target_dir=tmp_path / "site",
        cache_dir=tmp_path / "cache",
        abi="pcc-native",
    )

    assert result["ok"] is True
    installed_pkg = tmp_path / "site" / "demo_pkg"
    assert (installed_pkg / "core.py").exists()
    assert (installed_pkg / "generated.py").read_text(
        encoding="utf-8"
    ) == "BUILD_VALUE = 99\n"
    assert (installed_pkg / "_native.so").exists()
    assert (installed_pkg / "__init__.py").read_text(encoding="utf-8") == "VALUE = 2\n"
    assert (tmp_path / "cache" / "demo_pkg" / "generated.py").exists()


def test_local_install_can_build_source_before_overlay(tmp_path):
    project = _write_demo_project(tmp_path / "demo_pkg-0.1")
    _write_fake_vendored_meson(project)

    result = install_package(
        str(project),
        target_dir=tmp_path / "site",
        cache_dir=tmp_path / "cache",
        abi="pcc-native",
        build_source=True,
        build_mode="host",
    )

    assert result["ok"] is True
    assert result["build_report"]["ok"] is True
    assert result["build_report"]["build_ownership"] == "host"
    assert result["build_report"]["host_python"] == sys.executable
    assert result["build_report"]["host_free_build_claim"] is False
    assert [action["kind"] for action in result["build_report"]["actions"]] == [
        "meson_setup",
        "meson_build",
    ]
    assert (tmp_path / "site" / "demo_pkg" / "generated.py").exists()
    assert (tmp_path / "site" / "demo_pkg" / "__init__.py").read_text(
        encoding="utf-8"
    ) == "VALUE = 2\n"


def test_cython_tool_wrapper_does_not_discover_the_package_project():
    wrappers = _build_requirement_tool_wrappers(("Cython>=3.0.6",))
    assert wrappers is not None
    try:
        script = (Path(wrappers.name) / "cython").read_text(encoding="utf-8")
    finally:
        wrappers.cleanup()

    assert "uv run --no-project --with 'Cython>=3.0.6' cython" in script


def test_install_blocks_libpython_linked_artifact_in_pcc_native_mode(tmp_path):
    wheelhouse = tmp_path / "wheelhouse"
    wheelhouse.mkdir()
    wheel = _write_demo_wheel(
        wheelhouse / "demo_pkg-0.1-py3-none-any.whl",
        native_libpython=True,
    )

    result = install_package(
        str(wheel),
        target_dir=tmp_path / "site",
        cache_dir=tmp_path / "cache",
        abi="pcc-native",
    )
    assert result["ok"] is False
    assert result["links_libpython"] is True
    assert result["no_libpython_runtime"] is False
    assert result["link_libpython_edges"]
    assert result["diagnostics"][0]["code"] == "PCC-PKG-003"
    assert Path(result["manifest_path"]).exists()
    assert not (tmp_path / "cache" / "demo_pkg" / "pcc-package.json").exists()

    compat = install_package(
        str(wheel),
        target_dir=tmp_path / "site_libpython",
        cache_dir=tmp_path / "cache_libpython",
        abi="libpython",
    )
    assert compat["ok"] is True
    assert compat["links_libpython"] is True
    assert compat["no_libpython_runtime"] is False
    assert (tmp_path / "cache_libpython" / "demo_pkg" / "pcc-package.json").exists()


def test_install_blocks_cpython_extension_abi_in_pcc_native_mode(tmp_path):
    wheelhouse = tmp_path / "wheelhouse"
    wheelhouse.mkdir()
    wheel = _write_demo_wheel(
        wheelhouse / "demo_pkg-0.1-py3-none-any.whl",
        cpython_extension_abi=True,
    )

    result = install_package(
        str(wheel),
        target_dir=tmp_path / "site",
        cache_dir=tmp_path / "cache",
        abi="pcc-native",
    )
    assert result["ok"] is False
    assert result["links_libpython"] is False
    assert result["no_libpython_runtime"] is False
    assert result["diagnostics"][0]["code"] == "PCC-PKG-004"
    assert not (tmp_path / "cache" / "demo_pkg" / "pcc-package.json").exists()

    compat = install_package(
        str(wheel),
        target_dir=tmp_path / "site_compat",
        cache_dir=tmp_path / "cache_compat",
        abi="cpython-compat",
    )
    assert compat["ok"] is True
    assert compat["linkage"]["uses_cpython_extension_abi"] is True


def test_find_links_resolves_local_wheelhouse(tmp_path):
    wheelhouse = tmp_path / "wheelhouse"
    wheelhouse.mkdir()
    _write_demo_wheel(wheelhouse / "demo_pkg-0.2-py3-none-any.whl")
    _write_demo_wheel(wheelhouse / "demo_pkg-0.10-py3-none-any.whl")

    result = install_package(
        "demo_pkg",
        target_dir=tmp_path / "site",
        cache_dir=tmp_path / "cache",
        find_links=[str(wheelhouse)],
    )
    assert result["ok"] is True
    assert result["resolved_from"] == "find-links"
    assert (tmp_path / "site" / "demo_pkg" / "core.py").exists()
    assert (tmp_path / "cache" / "demo_pkg" / "core.py").exists()


def test_find_links_consumes_pcc_wheel_repository_manifest(tmp_path):
    wheelhouse = tmp_path / "wheelhouse"
    wheelhouse.mkdir()
    _write_demo_wheel(wheelhouse / "demo_pkg-0.1-py3-none-any.whl")
    native = _write_demo_wheel(
        wheelhouse / f"demo_pkg-0.1-{pcc_native_wheel_tag()}.whl"
    )
    report = repository_report(wheelhouse, write_manifest=True)
    assert report["ok"] is True

    result = install_package(
        "demo_pkg",
        target_dir=tmp_path / "site",
        cache_dir=tmp_path / "cache",
        find_links=[str(wheelhouse)],
    )
    assert result["ok"] is True
    assert result["resolved_from"] == "wheel-repository"
    assert result["source_path"] == str(native)
    assert result["no_libpython_runtime"] is True
    assert (tmp_path / "site" / "demo_pkg" / "core.py").exists()


def test_find_links_repository_manifest_skips_libpython_artifact(tmp_path):
    wheelhouse = tmp_path / "wheelhouse"
    wheelhouse.mkdir()
    pure = _write_demo_wheel(wheelhouse / "demo_pkg-0.1-py3-none-any.whl")
    _write_demo_wheel(
        wheelhouse / f"demo_pkg-0.2-{pcc_native_wheel_tag()}.whl",
        native_libpython=True,
    )
    report = repository_report(wheelhouse, write_manifest=True)
    assert report["ok"] is False

    result = install_package(
        "demo_pkg",
        target_dir=tmp_path / "site",
        cache_dir=tmp_path / "cache",
        find_links=[str(wheelhouse)],
    )
    assert result["ok"] is True
    assert result["resolved_from"] == "wheel-repository"
    assert result["source_path"] == str(pure)
    assert result["no_libpython_runtime"] is True


def test_find_links_prefers_highest_version_and_reports_unsupported_requirements(
    tmp_path,
):
    wheelhouse = tmp_path / "wheelhouse"
    wheelhouse.mkdir()
    _write_demo_wheel(wheelhouse / "demo_pkg-0.2-py3-none-any.whl")
    _write_demo_wheel(
        wheelhouse / "demo_pkg-0.10-py3-none-any.whl",
        requires=("helper-pkg[fast]>=2; python_version > '3.12'",),
    )

    result = install_package(
        "demo_pkg",
        target_dir=tmp_path / "site",
        cache_dir=tmp_path / "cache",
        find_links=[str(wheelhouse)],
    )
    assert result["ok"] is True
    assert result["source_path"].endswith("demo_pkg-0.10-py3-none-any.whl")
    assert result["dependency_diagnostics"] == [
        "unsupported_extras:helper-pkg",
        "unresolved_version_constraint:helper-pkg",
        "unsupported_environment_marker:helper-pkg",
    ]

    env = os.environ.copy()
    env.pop("LC_ALL", None)
    proc = subprocess.run(
        [
            "uv",
            "run",
            "pcc",
            "-m",
            "pip",
            "install",
            "demo_pkg",
            "--no-index",
            "--find-links",
            str(wheelhouse),
            "--dry-run",
        ],
        check=True,
        text=True,
        capture_output=True,
        timeout=60,
        env=env,
    )
    plan = json.loads(proc.stdout)
    assert plan["resolver_diagnostics"] == [
        "demo_pkg:unsupported_extras:helper-pkg",
        "demo_pkg:unresolved_version_constraint:helper-pkg",
        "demo_pkg:unsupported_environment_marker:helper-pkg",
    ]


def test_pcc_package_install_cli_and_pip_install_shape(tmp_path):
    project = _write_demo_project(tmp_path / "demo_pkg-0.1")
    site = tmp_path / "site"
    cache = tmp_path / "cache"
    env = os.environ.copy()
    env.pop("LC_ALL", None)
    proc = subprocess.run(
        [
            "uv",
            "run",
            "pcc",
            "-m",
            "pcc.package",
            "install",
            str(project),
            "--target",
            str(site),
            "--cache-dir",
            str(cache),
            "--json",
        ],
        check=True,
        text=True,
        capture_output=True,
        timeout=60,
        env=env,
    )
    result = json.loads(proc.stdout)
    assert result["ok"] is True
    assert Path(result["manifest_path"]).exists()
    assert (tmp_path / "site" / "demo_pkg" / "__init__.py").exists()

    proc = subprocess.run(
        [
            "uv",
            "run",
            "pcc",
            "-m",
            "pcc.package",
            "install",
            "demo_pkg",
            "--target",
            str(tmp_path / "site2"),
            "--cache-dir",
            str(tmp_path / "cache"),
            "--json",
        ],
        check=True,
        text=True,
        capture_output=True,
        timeout=60,
        env=env,
    )
    cached = json.loads(proc.stdout)
    assert cached["ok"] is True
    assert (tmp_path / "site2" / "demo_pkg" / "__init__.py").exists()
    assert (tmp_path / "site2" / "demo_pkg" / "core.py").exists()

    proc = subprocess.run(
        [
            "uv",
            "run",
            "pcc",
            "-m",
            "pip",
            "install",
            str(project),
            "--target",
            str(tmp_path / "site2"),
            "--cache-dir",
            str(cache),
        ],
        check=False,
        text=True,
        capture_output=True,
        timeout=60,
        env=env,
    )
    plan = json.loads(proc.stdout)
    assert proc.returncode == 2
    assert plan["ok"] is False
    assert plan["build_mode_requested"] == "owned"
    assert plan["installs"][0]["build_report"]["diagnostics"] == [
        "PCC-PKG-OWNED-BUILD-TOOL-REQUIRED"
    ]


def test_pcc_pip_install_find_links_wheelhouse(tmp_path):
    wheelhouse = tmp_path / "wheelhouse"
    wheelhouse.mkdir()
    _write_demo_wheel(wheelhouse / "demo_pkg-0.1-py3-none-any.whl")
    env = os.environ.copy()
    env.pop("LC_ALL", None)
    proc = subprocess.run(
        [
            "uv",
            "run",
            "pcc",
            "-m",
            "pip",
            "install",
            "demo_pkg",
            "--no-index",
            "--find-links",
            str(wheelhouse),
            "--target",
            str(tmp_path / "site"),
            "--cache-dir",
            str(tmp_path / "cache"),
        ],
        check=True,
        text=True,
        capture_output=True,
        timeout=60,
        env=env,
    )
    plan = json.loads(proc.stdout)
    assert plan["ok"] is True
    assert plan["find_links"] == [str(wheelhouse)]
    assert plan["installs"][0]["resolved_from"] == "find-links"
    assert (tmp_path / "site" / "demo_pkg" / "core.py").exists()


def test_pcc_pip_install_local_simple_index(tmp_path):
    index_root = tmp_path / "index"
    packages = index_root / "packages"
    packages.mkdir(parents=True)
    wheel = _write_demo_wheel(packages / "demo_pkg-0.1-py3-none-any.whl")
    simple_path = _write_simple_index(index_root, wheel)
    env = os.environ.copy()
    env.pop("LC_ALL", None)

    with _serve_directory(index_root) as base_url:
        index_url = base_url + simple_path
        proc = subprocess.run(
            [
                "uv",
                "run",
                "pcc",
                "-m",
                "pip",
                "install",
                "demo_pkg",
                "--acquire=owned",
                "--index-url",
                index_url,
                "--target",
                str(tmp_path / "site"),
                "--cache-dir",
                str(tmp_path / "cache"),
            ],
            check=True,
            text=True,
            capture_output=True,
            timeout=60,
            env=env,
        )

    plan = json.loads(proc.stdout)
    assert plan["ok"] is True
    assert plan["index_urls"] == [index_url]
    assert plan["acquisitions"][0]["artifact_origin"] == "simple-repository"
    assert plan["installs"][0]["resolved_from"] == "index-url"
    assert (
        plan["installs"][0]["source_path"] == plan["acquisitions"][0]["artifact_path"]
    )
    assert plan["installs"][0]["source_path"].endswith(wheel.name)
    assert (tmp_path / "site" / "demo_pkg" / "core.py").exists()
    acquired = Path(plan["acquisitions"][0]["artifact_path"])
    assert acquired.exists()
    assert acquired.parent.name == plan["acquisitions"][0]["sha256"]


def test_pcc_pip_dry_run_report_writes_install_plan(tmp_path):
    wheelhouse = tmp_path / "wheelhouse"
    wheelhouse.mkdir()
    _write_demo_wheel(wheelhouse / "demo_pkg-0.1-py3-none-any.whl")
    report_path = tmp_path / "install-report.json"
    env = os.environ.copy()
    env.pop("LC_ALL", None)
    proc = subprocess.run(
        [
            "uv",
            "run",
            "pcc",
            "-m",
            "pip",
            "install",
            "demo_pkg",
            "--no-index",
            "--find-links",
            str(wheelhouse),
            "--dry-run",
            "--report",
            str(report_path),
        ],
        check=True,
        text=True,
        capture_output=True,
        timeout=60,
        env=env,
    )
    plan = json.loads(proc.stdout)
    report = json.loads(report_path.read_text(encoding="utf-8"))
    assert plan["ok"] is True
    assert report["ok"] is True
    assert report["packages"] == ["demo_pkg"]
    assert report["report_path"] == str(report_path)


def test_pcc_pip_install_find_links_installs_local_dependencies(tmp_path):
    wheelhouse = tmp_path / "wheelhouse"
    wheelhouse.mkdir()
    _write_helper_wheel(wheelhouse / "helper_pkg-0.1-py3-none-any.whl")
    _write_demo_wheel(
        wheelhouse / "demo_pkg-0.1-py3-none-any.whl",
        requires=("helper-pkg",),
    )
    env = os.environ.copy()
    env.pop("LC_ALL", None)
    proc = subprocess.run(
        [
            "uv",
            "run",
            "pcc",
            "-m",
            "pip",
            "install",
            "demo_pkg",
            "--no-index",
            "--find-links",
            str(wheelhouse),
            "--target",
            str(tmp_path / "site"),
            "--cache-dir",
            str(tmp_path / "cache"),
        ],
        check=True,
        text=True,
        capture_output=True,
        timeout=60,
        env=env,
    )
    plan = json.loads(proc.stdout)
    assert plan["ok"] is True
    assert plan["packages"] == ["demo_pkg"]
    assert plan["install_specs"] == ["helper-pkg", "demo_pkg"]
    assert (tmp_path / "site" / "helper_pkg" / "core.py").exists()
    assert (tmp_path / "site" / "demo_pkg" / "core.py").exists()


def test_native_pcc1_owned_meson_source_reenters_receipt_bound_build_path(tmp_path):
    from pcc.cli_bootstrap import _native_build_install_source_json

    project = _write_demo_project(tmp_path / "demo_pkg-0.1")
    _write_demo_meson_build_overlay(project)

    report = json.loads(
        _native_build_install_source_json("demo_pkg", str(project), "pcc-native")
    )

    # meson.build makes this a source tree even when stale build outputs are
    # present.  Owned mode must re-enter the compiler/tool/source-bound receipt
    # path instead of accepting those outputs as authoritative prebuilt bytes.
    assert report["actions"] == []
    assert report["build_backend"] == "pcc-native-meson"
    assert report["build_mode_requested"] == "owned"
    assert report["build_ownership"] == "owned"
    assert report["diagnostics"] == [
        "PCC-PKG-OWNED-BUILD-COMPILER-REQUIRED"
    ]
    assert report["host_assisted"] is False
    assert report["host_free_build_claim"] is False
    assert report["host_python"] is None
    assert report["ok"] is False
    assert report["reason"] == "owned_build_compiler_required"
    assert report["skipped"] is False


def test_pcc1_package_install_labels_unproven_prebuilt_payload(tmp_path):
    pcc1 = _find_current_pcc1()
    if pcc1 is None:
        skip_or_fail_no_current_pcc1(
            "no current pcc1 binary with native package install shim"
        )
    project = _write_demo_project(tmp_path / "demo_pkg-0.1")
    env = os.environ.copy()
    env.pop("LC_ALL", None)
    env["PCC_PLATFORM_TAG"] = current_platform_tag()
    _write_demo_meson_build_overlay(project)
    proc = subprocess.run(
        [
            str(pcc1),
            "-m",
            "pcc.package",
            "install",
            str(project),
            "--target",
            str(tmp_path / "site"),
            "--cache-dir",
            str(tmp_path / "cache"),
            "--build=host",
            "--json",
        ],
        check=True,
        text=True,
        capture_output=True,
        timeout=30,
        env=env,
    )
    result = json.loads(proc.stdout)
    assert result["ok"] is True
    assert result["build_report"]["build_ownership"] == "prebuilt-unverified"
    assert result["build_report"]["host_free_build_claim"] is False
    assert Path(result["manifest_path"]).exists()
    assert (tmp_path / "site" / "demo_pkg" / "__init__.py").exists()
    assert (tmp_path / "site" / "demo_pkg" / "generated.py").exists()

    proc = subprocess.run(
        [
            str(pcc1),
            "-m",
            "pcc.package",
            "install",
            "demo_pkg",
            "--target",
            str(tmp_path / "site2"),
            "--cache-dir",
            str(tmp_path / "cache"),
            "--build=host",
            "--json",
        ],
        check=True,
        text=True,
        capture_output=True,
        timeout=30,
        env=env,
    )
    cached = json.loads(proc.stdout)
    assert cached["ok"] is True
    assert (tmp_path / "site2" / "demo_pkg" / "__init__.py").exists()
    assert (tmp_path / "site2" / "demo_pkg" / "core.py").exists()
    assert (tmp_path / "site2" / "demo_pkg" / "generated.py").exists()

    wheelhouse = tmp_path / "wheelhouse"
    wheelhouse.mkdir()
    _write_demo_wheel(wheelhouse / "demo_pkg-0.1-py3-none-any.whl")
    proc = subprocess.run(
        [
            str(pcc1),
            "-m",
            "pip",
            "install",
            "demo_pkg",
            "--no-index",
            "--find-links",
            str(wheelhouse),
            "--target",
            str(tmp_path / "site3"),
            "--cache-dir",
            str(tmp_path / "cache3"),
        ],
        check=True,
        text=True,
        capture_output=True,
        timeout=30,
        env=env,
    )
    plan = json.loads(proc.stdout)
    assert plan["ok"] is True
    assert plan["installs"][0]["source_path"].endswith("demo_pkg-0.1-py3-none-any.whl")
    assert (tmp_path / "site3" / "demo_pkg" / "core.py").exists()

    repo_wheelhouse = tmp_path / "repo_wheelhouse"
    repo_wheelhouse.mkdir()
    pure = _write_demo_wheel(repo_wheelhouse / "demo_pkg-0.1-py3-none-any.whl")
    _write_demo_wheel(
        repo_wheelhouse / f"demo_pkg-0.2-{pcc_native_wheel_tag()}.whl",
        native_libpython=True,
    )
    repository_report(repo_wheelhouse, write_manifest=True)
    proc = subprocess.run(
        [
            str(pcc1),
            "-m",
            "pcc.package",
            "install",
            "demo_pkg",
            "--find-links",
            str(repo_wheelhouse),
            "--target",
            str(tmp_path / "site_repo"),
            "--cache-dir",
            str(tmp_path / "cache_repo"),
            "--json",
        ],
        check=True,
        text=True,
        capture_output=True,
        timeout=30,
        env=env,
    )
    repo_install = json.loads(proc.stdout)
    assert repo_install["ok"] is True
    assert repo_install["resolved_from"] == "wheel-repository"
    assert repo_install["source_path"].endswith(pure.name)
    assert repo_install["no_libpython_runtime"] is True

    index_root = tmp_path / "index"
    packages = index_root / "packages"
    packages.mkdir(parents=True)
    wheel = _write_demo_wheel(packages / "demo_pkg-0.1-py3-none-any.whl")
    simple_path = _write_simple_index(index_root, wheel)
    with _serve_directory(index_root) as base_url:
        index_url = base_url + simple_path
        proc = subprocess.run(
            [
                str(pcc1),
                "-m",
                "pcc.package",
                "install",
                "demo_pkg",
                "--index-url",
                index_url,
                "--target",
                str(tmp_path / "site_index"),
                "--cache-dir",
                str(tmp_path / "cache_index"),
                "--json",
            ],
            check=True,
            text=True,
            capture_output=True,
            timeout=30,
            env=env,
        )
        pip_proc = subprocess.run(
            [
                str(pcc1),
                "-m",
                "pip",
                "install",
                "demo_pkg",
                "--acquire=owned",
                "--index-url",
                index_url,
                "--target",
                str(tmp_path / "site_index_pip"),
                "--cache-dir",
                str(tmp_path / "cache_index_pip"),
            ],
            check=True,
            text=True,
            capture_output=True,
            timeout=30,
            env=env,
        )
    index_install = json.loads(proc.stdout)
    assert index_install["ok"] is True
    assert index_install["resolved_from"] == "index-url"
    assert index_install["source_path"].endswith(wheel.name)
    assert index_install["no_libpython_runtime"] is True
    assert (tmp_path / "site_index" / "demo_pkg" / "core.py").exists()
    pip_index_plan = json.loads(pip_proc.stdout)
    assert pip_index_plan["ok"] is True
    assert pip_index_plan["installs"][0]["resolved_from"] == "index-url"
    assert (tmp_path / "site_index_pip" / "demo_pkg" / "core.py").exists()

    dep_wheelhouse = tmp_path / "dep_wheelhouse"
    dep_wheelhouse.mkdir()
    _write_helper_wheel(dep_wheelhouse / "helper_pkg-0.1-py3-none-any.whl")
    _write_demo_wheel(
        dep_wheelhouse / "demo_pkg-0.1-py3-none-any.whl",
        requires=("helper-pkg",),
    )
    proc = subprocess.run(
        [
            str(pcc1),
            "-m",
            "pip",
            "install",
            "demo_pkg",
            "--no-index",
            "--find-links",
            str(dep_wheelhouse),
            "--target",
            str(tmp_path / "site4"),
            "--cache-dir",
            str(tmp_path / "cache4"),
        ],
        check=True,
        text=True,
        capture_output=True,
        timeout=30,
        env=env,
    )
    plan = json.loads(proc.stdout)
    assert plan["ok"] is True
    assert (tmp_path / "site4" / "helper_pkg" / "core.py").exists()
    assert (tmp_path / "site4" / "demo_pkg" / "core.py").exists()

    report_path = tmp_path / "pcc1-report.json"
    proc = subprocess.run(
        [
            str(pcc1),
            "-m",
            "pip",
            "install",
            "demo_pkg",
            "--no-index",
            "--find-links",
            str(wheelhouse),
            "--dry-run",
            "--report",
            str(report_path),
        ],
        check=True,
        text=True,
        capture_output=True,
        timeout=30,
        env=env,
    )
    report_plan = json.loads(proc.stdout)
    report = json.loads(report_path.read_text(encoding="utf-8"))
    assert report_plan["ok"] is True
    assert report["ok"] is True
    assert report["report_path"] == str(report_path)

    bad_wheel = _write_demo_wheel(
        tmp_path / "demo_pkg-0.2-py3-none-any.whl",
        native_libpython=True,
    )
    proc = subprocess.run(
        [
            str(pcc1),
            "-m",
            "pcc.package",
            "install",
            str(bad_wheel),
            "--target",
            str(tmp_path / "bad_site"),
            "--cache-dir",
            str(tmp_path / "bad_cache"),
            "--json",
        ],
        text=True,
        capture_output=True,
        timeout=30,
        env=env,
    )
    assert proc.returncode == 2
    bad_result = json.loads(proc.stdout)
    assert bad_result["ok"] is False
    assert bad_result["links_libpython"] is True
    assert bad_result["no_libpython_runtime"] is False
    assert bad_result["diagnostics"][0]["code"] == "PCC-PKG-003"
