from __future__ import annotations

import json
import os
import subprocess
from pathlib import Path

import pytest

from pcc1_gate import find_current_pcc1, skip_or_fail_no_current_pcc1

from pcc.package.build_plan import (
    build_plan_for_artifact,
    load_compile_commands,
    load_meson_introspection_commands,
)


REPO = Path(__file__).resolve().parents[2]
def _find_current_pcc1() -> Path | None:
    return find_current_pcc1(REPO)


def _write_build_project(root: Path) -> Path:
    root.mkdir()
    (root / "demo_pkg").mkdir()
    (root / "demo_pkg" / "__init__.py").write_text("VALUE = 1\n", encoding="utf-8")
    (root / "demo_pkg.pyx").write_text("cdef int value\n", encoding="utf-8")
    (root / "demo_pkg.c").write_text(
        "/* Generated by Cython */\nint demo(void) { return 1; }\n",
        encoding="utf-8",
    )
    (root / "solver.f90").write_text("subroutine solver()\nend\n", encoding="utf-8")
    (root / "meson.build").write_text("project('demo_pkg', 'c')\n", encoding="utf-8")
    (root / "pyproject.toml").write_text(
        "[build-system]\n"
        "requires = ['meson-python', 'cython']\n"
        "build-backend = 'mesonpy'\n",
        encoding="utf-8",
    )
    (root / "compile_commands.json").write_text(
        json.dumps(
            [
                {
                    "file": str(root / "demo_pkg.c"),
                    "command": "cc -I include -DVALUE=1 -c demo_pkg.c -o demo_pkg.o -lopenblas",
                },
                {
                    "file": str(root / "solver.f90"),
                    "arguments": [
                        "gfortran",
                        "-I",
                        "finclude",
                        "-c",
                        "solver.f90",
                        "-o",
                        "solver.o",
                        "-llapack",
                    ],
                },
            ]
        ),
        encoding="utf-8",
    )
    return root


def _write_meson_only_project(root: Path) -> Path:
    root.mkdir()
    (root / "demo_pkg").mkdir()
    (root / "demo_pkg" / "__init__.py").write_text("VALUE = 1\n", encoding="utf-8")
    (root / "native.c").write_text("int native_value(void) { return 1; }\n", encoding="utf-8")
    (root / "solver.f90").write_text("subroutine solver()\nend\n", encoding="utf-8")
    (root / "meson.build").write_text("project('demo_pkg', 'c', 'fortran')\n", encoding="utf-8")
    meson_info = root / "meson-info"
    meson_info.mkdir()
    (meson_info / "intro-targets.json").write_text(
        json.dumps(
            [
                {
                    "name": "demo_native",
                    "target_sources": [
                        {
                            "language": "c",
                            "compiler": ["cc"],
                            "parameters": ["-DMESON_VALUE=1"],
                            "sources": ["native.c"],
                        },
                        {
                            "language": "fortran",
                            "compiler": ["gfortran"],
                            "parameters": [],
                            "sources": ["solver.f90"],
                        },
                    ],
                }
            ]
        ),
        encoding="utf-8",
    )
    return root


def test_build_plan_consumes_compile_commands_and_build_surfaces(tmp_path):
    project = _write_build_project(tmp_path / "demo_pkg-0.1")
    commands = load_compile_commands(project / "compile_commands.json")
    assert [command.language for command in commands] == ["c", "fortran"]
    assert commands[0].include_dirs == ("include",)
    assert commands[0].defines == ("VALUE=1",)
    assert commands[0].libraries == ("openblas",)
    assert commands[1].include_dirs == ("finclude",)
    assert commands[1].libraries == ("lapack",)

    plan = build_plan_for_artifact("demo-pkg", project).as_dict()
    assert plan["ok"] is True
    assert plan["source_summary"] == {"c": 1, "cxx": 0, "fortran": 1, "unknown": 0}
    assert "consume_compile_commands" in plan["actions"]
    assert "consume_generated_c" in plan["actions"]
    assert "consume_meson_plan" in plan["actions"]
    assert "delegate_fortran_toolchain" in plan["actions"]
    assert "detect_blas" in plan["actions"]
    assert "detect_lapack" in plan["actions"]
    assert "fortran_toolchain_required" in plan["diagnostics"]
    assert "blas_vendor_required" in plan["diagnostics"]
    assert "lapack_vendor_required" in plan["diagnostics"]


def test_build_plan_consumes_meson_introspection_when_compile_commands_absent(tmp_path):
    project = _write_meson_only_project(tmp_path / "demo_pkg-0.1")
    commands = load_meson_introspection_commands(project)
    assert [command.language for command in commands] == ["c", "fortran"]
    assert commands[0].defines == ("MESON_VALUE=1",)
    assert commands[0].output.endswith("native_0.o")
    assert commands[1].output.endswith("solver_1.o")

    plan = build_plan_for_artifact("demo-pkg", project).as_dict()
    assert plan["ok"] is True
    assert plan["source_summary"] == {"c": 1, "cxx": 0, "fortran": 1, "unknown": 0}
    assert "consume_meson_introspection" in plan["actions"]
    assert "consume_meson_plan" in plan["actions"]
    assert "delegate_fortran_toolchain" in plan["actions"]


def test_build_plan_finds_pcc_package_meson_build_dir(tmp_path):
    project = _write_meson_only_project(tmp_path / "demo_pkg-0.1")
    generated = project / "build" / "pcc-package" / "meson-build" / "meson-info"
    generated.mkdir(parents=True)
    original = project / "meson-info" / "intro-targets.json"
    (generated / "intro-targets.json").write_text(original.read_text(encoding="utf-8"), encoding="utf-8")
    original.unlink()

    commands = load_meson_introspection_commands(project)
    assert [command.language for command in commands] == ["c", "fortran"]
    assert "meson-build/build/pcc-package" not in commands[0].output
    plan = build_plan_for_artifact("demo-pkg", project).as_dict()
    assert "consume_meson_introspection" in plan["actions"]
    assert plan["source_summary"]["c"] == 1


def test_build_plan_excludes_docs_tests_and_vendored_examples(tmp_path):
    project = tmp_path / "demo_pkg-0.1"
    project.mkdir()
    (project / "demo_pkg").mkdir()
    (project / "demo_pkg" / "__init__.py").write_text("VALUE = 1\n", encoding="utf-8")
    (project / "demo_pkg" / "_native.pyx").write_text("cdef int value\n", encoding="utf-8")
    (project / "meson.options").write_text(
        "option('allow-noblas', type: 'boolean', value: true,\n"
        "        description: 'allow internal fallback routines')\n",
        encoding="utf-8",
    )
    (project / "doc" / "examples").mkdir(parents=True)
    (project / "doc" / "examples" / "solver.f90").write_text("subroutine demo()\nend\n", encoding="utf-8")
    (project / "tests" / "examples").mkdir(parents=True)
    (project / "tests" / "examples" / "checks.pyx").write_text("cdef int ignored\n", encoding="utf-8")
    (project / "vendored-meson" / "meson" / "test cases" / "cython").mkdir(parents=True)
    (project / "vendored-meson" / "meson" / "test cases" / "cython" / "storer.pyx").write_text(
        "cdef int ignored\n",
        encoding="utf-8",
    )
    (project / "vendored-meson" / "meson" / "test cases" / "cython" / "storer.c").write_text(
        "/* Generated by Cython */\n",
        encoding="utf-8",
    )

    plan = build_plan_for_artifact("demo-pkg", project).as_dict()
    assert "cython_regeneration_required" in plan["diagnostics"]
    assert "fortran_toolchain_required" not in plan["diagnostics"]
    assert "delegate_fortran_toolchain" not in plan["actions"]
    assert "consume_generated_c" not in plan["actions"]
    assert plan["metadata"]["cython_sources"] == ["demo_pkg/_native.pyx"]
    assert plan["metadata"]["fortran_sources"] == []


def test_build_plan_treats_allow_noblas_as_optional_vendor_binding(tmp_path):
    project = tmp_path / "demo_pkg-0.1"
    project.mkdir()
    (project / "demo_pkg").mkdir()
    (project / "demo_pkg" / "__init__.py").write_text("VALUE = 1\n", encoding="utf-8")
    (project / "demo_pkg" / "blas_probe.c").write_text("int blas_probe(void) { return 0; }\n", encoding="utf-8")
    (project / "demo_pkg" / "lapack_probe.c").write_text("int lapack_probe(void) { return 0; }\n", encoding="utf-8")
    (project / "meson.build").write_text("project('demo_pkg', 'c')\n", encoding="utf-8")
    (project / "meson.options").write_text(
        "option('allow-noblas', type: 'boolean', value: true,\n"
        "        description: 'allow internal fallback routines')\n",
        encoding="utf-8",
    )

    plan = build_plan_for_artifact("demo-pkg", project).as_dict()
    assert "detect_blas" in plan["actions"]
    assert "detect_lapack" in plan["actions"]
    assert "blas_vendor_required" not in plan["diagnostics"]
    assert "lapack_vendor_required" not in plan["diagnostics"]
    assert plan["metadata"]["native_library_fallbacks"] == ["blas", "lapack"]


def test_pcc_package_build_plan_cli(tmp_path):
    project = _write_build_project(tmp_path / "demo_pkg-0.1")
    env = os.environ.copy()
    env.pop("LC_ALL", None)
    proc = subprocess.run(
        [
            "uv",
            "run",
            "pcc",
            "-m",
            "pcc.package",
            "build-plan",
            "demo-pkg",
            "--path",
            str(project),
            "--json",
        ],
        check=True,
        text=True,
        capture_output=True,
        timeout=30,
        env=env,
    )
    plan = json.loads(proc.stdout)
    assert plan["ok"] is True
    assert plan["source_summary"]["fortran"] == 1
    assert plan["commands"][0]["compiler"] == "cc"


def test_pcc1_build_plan_excludes_non_build_tree_surfaces(tmp_path):
    pcc1 = _find_current_pcc1()
    if pcc1 is None:
        skip_or_fail_no_current_pcc1("no current pcc1 binary with native build-plan shim")
    project = tmp_path / "demo_pkg-0.1"
    project.mkdir()
    (project / "demo_pkg").mkdir()
    (project / "demo_pkg" / "__init__.py").write_text("VALUE = 1\n", encoding="utf-8")
    (project / "demo_pkg" / "_native.pyx").write_text("cdef int value\n", encoding="utf-8")
    (project / "meson.options").write_text(
        "option('allow-noblas', type: 'boolean', value: true,\n"
        "        description: 'allow internal fallback routines')\n",
        encoding="utf-8",
    )
    (project / "doc" / "examples").mkdir(parents=True)
    (project / "doc" / "examples" / "solver.f90").write_text("subroutine demo()\nend\n", encoding="utf-8")
    (project / "vendored-meson" / "meson" / "test cases" / "cython").mkdir(parents=True)
    (project / "vendored-meson" / "meson" / "test cases" / "cython" / "storer.pyx").write_text(
        "cdef int ignored\n",
        encoding="utf-8",
    )
    (project / "vendored-meson" / "meson" / "test cases" / "cython" / "storer.c").write_text(
        "/* Generated by Cython */\n",
        encoding="utf-8",
    )
    env = os.environ.copy()
    env.pop("LC_ALL", None)
    env["PCC_HOST_PYTHON"] = "/bin/false"
    proc = subprocess.run(
        [
            str(pcc1),
            "-m",
            "pcc.package",
            "build-plan",
            "demo-pkg",
            "--path",
            str(project),
            "--json",
        ],
        check=True,
        text=True,
        capture_output=True,
        timeout=30,
        env=env,
    )
    plan = json.loads(proc.stdout)
    assert "cython_regeneration_required" in plan["diagnostics"]
    assert "fortran_toolchain_required" not in plan["diagnostics"]
    assert "delegate_fortran_toolchain" not in plan["actions"]
    assert plan["source_summary"]["fortran"] == 0
    assert plan["metadata"]["native_library_fallbacks"] == ["blas", "lapack"]


def test_pcc1_build_plan_does_not_need_host_python(tmp_path):
    pcc1 = _find_current_pcc1()
    if pcc1 is None:
        skip_or_fail_no_current_pcc1("no current pcc1 binary with native build-plan shim")
    project = _write_build_project(tmp_path / "demo_pkg-0.1")
    env = os.environ.copy()
    env.pop("LC_ALL", None)
    env["PCC_HOST_PYTHON"] = "/bin/false"
    proc = subprocess.run(
        [
            str(pcc1),
            "-m",
            "pcc.package",
            "build-plan",
            "demo-pkg",
            "--path",
            str(project),
            "--json",
        ],
        check=True,
        text=True,
        capture_output=True,
        timeout=30,
        env=env,
    )
    plan = json.loads(proc.stdout)
    assert plan["ok"] is True
    assert plan["compile_commands"]["entries"] == 2
    assert plan["compile_commands"]["c_entries"] == 1
    assert plan["compile_commands"]["fortran_entries"] == 1
    assert plan["source_summary"]["fortran"] == 1
