/* Generated by scripts/gen_freestanding_stdio_abi.py. */
#ifndef PCC_STDIO_ABI_H
#define PCC_STDIO_ABI_H

#include <stddef.h>
#include <stdint.h>

typedef struct PccOwnedFile {
    uint64_t magic;
    int64_t fd;
    uint64_t flags;
    int64_t aux;
    void * buffer;
    uint64_t buffer_capacity;
    uint64_t buffer_length;
    int64_t buffer_position;
} PccOwnedFile;

#define PCC_STDIO_FILE_MAGIC 5783538579059651889ULL
#define PCC_STDIO_FILE_SIZE 64
#define PCC_STDIO_FLAG_READABLE 1ULL
#define PCC_STDIO_FLAG_WRITABLE 2ULL
#define PCC_STDIO_FLAG_ERROR 4ULL
#define PCC_STDIO_FLAG_EOF 8ULL
#define PCC_STDIO_FLAG_STANDARD 16ULL
#define PCC_STDIO_FLAG_APPEND 32ULL

_Static_assert(offsetof(PccOwnedFile, magic) == 0, "PccOwnedFile.magic ABI");
_Static_assert(offsetof(PccOwnedFile, fd) == 8, "PccOwnedFile.fd ABI");
_Static_assert(offsetof(PccOwnedFile, flags) == 16, "PccOwnedFile.flags ABI");
_Static_assert(offsetof(PccOwnedFile, aux) == 24, "PccOwnedFile.aux ABI");
_Static_assert(offsetof(PccOwnedFile, buffer) == 32, "PccOwnedFile.buffer ABI");
_Static_assert(offsetof(PccOwnedFile, buffer_capacity) == 40, "PccOwnedFile.buffer_capacity ABI");
_Static_assert(offsetof(PccOwnedFile, buffer_length) == 48, "PccOwnedFile.buffer_length ABI");
_Static_assert(offsetof(PccOwnedFile, buffer_position) == 56, "PccOwnedFile.buffer_position ABI");
_Static_assert(sizeof(PccOwnedFile) == 64, "PccOwnedFile size ABI");

#endif
