#ifndef _FAKE_TARGETCONDITIONALS_H
#define _FAKE_TARGETCONDITIONALS_H

#ifndef TARGET_OS_EMBEDDED
#define TARGET_OS_EMBEDDED 0
#endif

#ifndef TARGET_IPHONE_SIMULATOR
#define TARGET_IPHONE_SIMULATOR 0
#endif

#ifndef TARGET_OS_MACCATALYST
#define TARGET_OS_MACCATALYST 0
#endif

#endif
