s = "hello world"
print(s)
print(len(s))
print(s[0], s[-1], s[6])
print(s[0:5])
print(s[6:])
print(s.upper())
print(s.lower())
print(s.split())
parts = "a=b=c".split("=", 1)
print(parts[0], parts[1])
ws = "  a  b  c ".split(None, 1)
print(ws[0], ws[1])
print(s.replace("world", "pcc"))
print(s.startswith("hello"), s.endswith("world"))
print(",".join(["a", "b", "c"]))
print("-".join(s.split()))
