"""Closed-world host contracts for Python codegen mixins.

The native lowering files under ``pcc.py_frontend.codegen.native_*`` are
mixins. A raw single-file probe sees ``self`` as the mixin class, but the
real closed-world compiler executes those methods on ``L1CodeGen``. Keep
that policy in one small codegen-local module so fallback gates and future
type-infer protocol work agree on the same host model.
"""

from __future__ import annotations

PROBE_POLICY_STANDALONE = "standalone"
PROBE_POLICY_CONTEXTUAL_MIXIN = "contextual-mixin"
PROBE_POLICY_CLOSED_WORLD = "closed-world"

L1_CODEGEN_HOST_CLASS = "pcc.py_frontend.codegen.layer1.L1CodeGen"
L1_CODEGEN_HOST_ATTRS = (
    "_NOOP_DECORATOR_BARE",
    "_NOOP_DECORATOR_QUALIFIED",
    "_active_handler_excs",
    "_ast_body",
    "_async_body_depth",
    "_attr_pool",
    "_box_int_locals",
    "_c_abi_export_symbols",
    "_class_aliases",
    "_class_attr_mutation_in_loop_depth",
    "_class_attr_runtime_state",
    "_class_type_export_cache",
    "_closure_boxed_params",
    "_cpy_env_flags",
    "_cpy_init_emitted_fns",
    "_cpy_module_env",
    "_cpy_module_flags",
    "_owned_cpy_values",
    "_cpy_operand_cleanup_block",
    "_cpy_star_module_env",
    "_cpy_values",
    "_container_temp_root_slot_names",
    "_cross_module_func_defs",
    "_cross_module_identity_decorators",
    "_cross_module_semantic_functions",
    "_cstr_counter",
    "_cstr_pool",
    "_current_global_names",
    "_current_entry_block",
    "_current_param_names",
    "_debug_release_checks",
    "_di_compile_unit",
    "_di_file",
    "_di_scope",
    "_di_subprograms",
    "_direct_indexed_module",
    "_duplicate_module_function_names",
    "_emitting_finally",
    "_exact_int_env_flags",
    "_boxed_int_module_global_names",
    "_planned_exact_int_local_names",
    "_entry_alloca_insert_before_function",
    "_entry_alloca_insert_index",
    "_entry_inline_edge_anchor_function",
    "_entry_inline_edge_anchor_record",
    "_direct_frame_landings",
    "_tb_index_lines",
    "_tb_index_sources",
    "_tb_index_by_file",
    "_tb_lines_global",
    "_tb_sources_global",
    "_except_binding_names",
    "_extern_bindings",
    "_extern_decls",
    "_finally_stack",
    "_fmt_bool_false",
    "_fmt_bool_true",
    "_fmt_float",
    "_fmt_int",
    "_fn_err_exit_blocks",
    "_fn_err_exit_gc_root_names",
    "_fn_err_exit_for_target_slots",
    "_fn_gc_root_slot_registry",
    "_fn_gc_root_exit_sites",
    "_fn_err_exit_gc_root_slots",
    "_fn_valueclass_payload_root_slots",
    "_funcdef_functions",
    "_funcdef_yield_sentinel_cache",
    "_vthread_binding_cache",
    "_function_definition_ordinals",
    "_for_target_owned_names",
    "_gc_rooted_local_names",
    "_gc_rooted_local_order",
    "_borrowed_gc_rooted_local_names",
    "_generator_ctx_stack",
    "_generator_func_names",
    "_vthread_may_park_func_ids",
    "_vthread_may_park_func_names",
    "_vthread_may_park_method_ids",
    "_vthread_may_park_method_keys",
    "_vthread_rejected_park_boundaries",
    "_hoist_wrap_caps",
    "_hoisted_capture_params",
    "_hoisted_class_capture_params",
    "_hoisted_enclosing_class",
    "_hoisted_enclosing_method_kind",
    "_ir_builder_env_flags",
    "_inspect_fullargspec_aliases",
    "_inspect_signature_aliases",
    "_lambda_counter",
    "_lambda_lexical_shadow_names",
    "_last_call_arg_owned_temp",
    "_last_fresh_direct_native_ctor_value",
    "_literal_dict_expr_bindings",
    "_virtual_literal_dict_expr_bindings",
    "_module_del_target_names",
    "_module_globals",
    "_module_global_init_flags",
    "_module_source_path",
    "_target_triple",
    "_method_mro_cache",
    "_module_block_func_defs",
    "_module_block_funcdef_ids",
    "_module_has_c_abi_export",
    "_module_uses_raw_int_scaffold",
    "_native_class_export_index",
    "_native_class_export_index_source",
    "_native_builtin_module_aliases",
    "_native_builtin_value_aliases",
    "_native_extension_star_module_env",
    "_native_file_env_flags",
    "_native_fileinput_env_flags",
    "_native_fileinput_values",
    "_native_file_values",
    "_native_lambda_callback_counter",
    "_native_lambda_func_counter",
    "_native_extension_module_env",
    "_native_module_aliases",
    "_native_module_attr_globals",
    "_native_module_constant_bindings",
    "_native_module_exports",
    "_native_symbol_funcdefs",
    "_native_function_object_exports",
    "_native_module_object_aliases",
    "_native_re_compile_aliases",
    "_native_re_compile_local_aliases",
    "_native_re_static_flag_aliases",
    "_never_gc_object_values",
    "_owned_local_flag_allocas",
    "_owned_local_flag_slots",
    "_owned_local_has_value",
    "_owned_dynamic_call_values",
    "_owned_local_names",
    "_pinned_gc_rooted_local_names",
    "_post_call_frame_blocks",
    "_prefer_native_callable_values",
    "_printf",
    "_python_library",
    "_runtime_threads_enabled",
    "_self_receiver_class_name_cache",
    "_sibling_module_inits",
    "_skip_program_main",
    "_source_file_lines_cache",
    "_freestanding_module",
    "_runtime_port_module",
    "_global_backed_values",
    "_suppress_borrowed_return_retain",
    "_suppress_implicit_gc_roots",
    "_codegen_current_expr_kind",
    "_codegen_current_stmt_index",
    "_codegen_current_stmt_kind",
    "_codegen_current_module_name",
    "_codegen_trace_diagnosed",
    "_codegen_trace_enabled",
    "_codegen_trace_next",
    "_codegen_trace_ring",
    "_codegen_trace_capacity",
    "_static_literal_init_fn",
    "_str_counter",
    "_str_obj_pool",
    "_str_pool",
    "_strict_no_libpython",
    "_thread_safepoints_enabled",
    "_threading_env_flags",
    "_threading_list_elem_flags",
    "_tmp_counter",
    "_try_err_block",
    "_typed_int_abi_call_arg_safety",
    "_bounded_int_abi_function_names",
    "_typing_metadata_aliases",
    "_typing_optional_aliases",
    "_typing_typevar_aliases",
    "_unboxed_typed_int_abi_cache",
    "_unsafe_bindings",
    "_weak_dict_env_flags",
    "_weakref_env_flags",
    "ast_module",
    "builder",
    "class_lowering",
    "current_class",
    "current_func_def",
    "current_function",
    "current_method_kind",
    "emit_cpy_main_exitcode",
    "env",
    "env_class_hint",
    "env_class_object_hint",
    "env_list_elem_class_hint",
    "functions",
    "ir_scaffold_mode",
    "loop_stack",
    "module",
    "runtime",
)
L1_CODEGEN_HOST_METHODS = (
    "_alloca_in_entry",
    "_as_gc_ptr",
    "_attr_expr_returns_owned_object",
    "_builder_block_is_terminated",
    "_call_user",
    "_callable_expr_returns_cpython",
    "_class_attr_descriptor_class",
    "_class_hint_for_expr",
    "_class_hint_from_annotation",
    "_coerce",
    "_collect_explicit_global_names",
    "_collect_return_exprs",
    "_container_store_temp_needs_release",
    "_pcc_pointer_source_needs_pin",
    "_cpy_module_global",
    "_cpy_modules",
    "_cstr_global",
    "_cstr_literal",
    "_current_try_err_block",
    "_debug_check_release",
    "_declare_external_function",
    "_declare_module_globals_for",
    "_declare_printf",
    "_decorator_c_abi_export_symbol",
    "_decorator_c_abi_typed_signature",
    "_decorator_is_noop_whitelist",
    "_decorator_is_runtime_partial_factory",
    "_decorator_qualname",
    "_decorator_repr",
    "_discard_owned_local_gc_root",
    "_emit_as_object",
    "_emit_arg_for_abi_param",
    "_emit_arg_for_abi_param_with_cleanup",
    "_emit_builtin_runtime_isinstance",
    "_emit_call_args_tuple",
    "_emit_class_global_root_enters",
    "_emit_comprehension_generator",
    "_emit_comprehension_innermost",
    "_emit_coroutine_from_adapter",
    "_emit_cpy_attr",
    "_emit_cpy_attr_with_cleanup",
    "_emit_cpy_method_call1_value",
    "_emit_cpython_dict_items",
    "_emit_cpython_list_ops",
    "_emit_cpython_tuple_ops",
    "_emit_current_gc_frame_enter",
    "_emit_current_gc_frame_enter_lifo",
    "_emit_dict_literal",
    "_emit_dynamic_call_args_tuple",
    "_emit_virtual_thread_container_call_check",
    "_emit_virtual_thread_dynamic_args_with_roots",
    "_emit_virtual_thread_rooted_args_tuple",
    "_emit_dynamic_call_kwargs_object",
    "_binop_route_defers_pins",
    "_emit_binop_value_routed",
    "_emit_dyn_tagged_int_object_binop",
    "_emit_empty_tuple",
    "_emit_entry_gc_frame_enter",
    "_emit_post_call_error_cleanup",
    "_direct_frame_landing",
    "_finalize_traceback_index_tables",
    "_traceback_index_for",
    "_traceback_source_text",
    "_emit_exact_container_subscript_load_object",
    "_emit_exact_int_compare",
    "_emit_exact_int_operand_object",
    "_emit_expr",
    "_emit_expr_as_i64",
    "_emit_expr_as_pcc_object",
    "_emit_expr_stmt",
    "_emit_expr_with_native_callable_values",
    "_emit_gc_frame_leave_for_slot",
    "_emit_gc_frame_leave_lifo_for_slot",
    "_enter_container_temp_root",
    "_emit_inline_tagged_int_binop_or_call",
    "_emit_ir_scaffold_isinstance",
    "_emit_isinstance_call",
    "_emit_runtime_object_compare",
    "_emit_module_global_root_enters",
    "_emit_module_root_enters",
    "_emit_module_teardown",
    "_emit_module_teardown_call",
    "_emit_module_top_init",
    "_emit_static_literal_init_call",
    "_finalize_static_literal_init",
    "_static_literal_init_function",
    "_emit_method_arg_as_pcc_object",
    "_emit_name",
    "_emit_native_builtin_callable_type_error",
    "_emit_native_builtin_callable_value",
    "_emit_native_func_adapter",
    "_emit_native_func_value",
    "_emit_native_os_environ_setitem_store",
    "_emit_native_os_environ_setitem_value",
    "_emit_native_os_environ_subscript",
    "_emit_native_os_call",
    "_emit_virtual_thread_callback_call",
    "_emit_virtual_thread_current_fd_wait",
    "_emit_virtual_thread_tcp_abandon_state",
    "_emit_virtual_thread_tcp_accept",
    "_emit_virtual_thread_tcp_arg_i64",
    "_emit_virtual_thread_tcp_arg_item",
    "_emit_virtual_thread_tcp_cleanup_block",
    "_emit_virtual_thread_tcp_capture_generation",
    "_emit_virtual_thread_tcp_clear_state",
    "_emit_virtual_thread_tcp_close",
    "_emit_virtual_thread_tcp_connect",
    "_emit_virtual_thread_tcp_listen",
    "_emit_virtual_thread_tcp_owned_i64",
    "_emit_virtual_thread_tcp_park_retry",
    "_emit_virtual_thread_tcp_recv",
    "_emit_virtual_thread_tcp_send_all",
    "_emit_virtual_thread_tcp_set_progress",
    "_emit_virtual_thread_tcp_set_state_i64",
    "_emit_virtual_thread_tcp_state",
    "_emit_virtual_thread_tcp_state_i64",
    "_emit_virtual_thread_tcp_state_item",
    "_emit_virtual_thread_tcp_status_guard",
    "_enter_virtual_thread_operand_root",
    "_emit_native_virtual_thread_call",
    "_emit_native_virtual_thread_value_call",
    "_load_virtual_thread_operand_root",
    "_release_virtual_thread_argument",
    "_release_rooted_pcc_lifetimes",
    "_emit_none_literal",
    "_emit_object_tuple_from_values",
    "_emit_operator_getter",
    "_emit_owned_local_cleanup",
    "_emit_pcc_args_list",
    "_emit_post_call_err_check",
    "_emit_print_float_value",
    "_emit_print_many",
    "_emit_program_main",
    "_emit_release_owned_local_if_flagged",
    "_emit_stmts",
    "_emit_strict_no_libpython_import_error",
    "_emit_str_literal",
    "_emit_unary",
    "_emit_value_as_pcc_object_or_bridge",
    "_emit_value_array_subscript_load",
    "_emit_virtual_thread_resume_function",
    "_emit_virtual_thread_spawn",
    "_emit_walrus",
    "_ensure_class_type_registered",
    "_ensure_fn_err_exit",
    "_ensure_module_global_name",
    "_ensure_native_module_alias_class_export",
    "_ensure_borrowed_local_gc_root",
    "_ensure_local_gc_frame_root",
    "_ensure_owned_local_flag",
    "_ensure_owned_local_gc_root",
    "_owned_local_flag_for",
    "_expr_looks_cpython",
    "_expr_returns_owned_object",
    "_pcc_pointer_source_is_owned",
    "_expr_returns_unsafe_raw_pointer",
    "_find_user_funcdef",
    "_finish_cpy_call_kw",
    "_fresh",
    "_func_decorators",
    "_funcdef_has_yield_sentinel",
    "_funcdef_uses_boxed_int_abi",
    "_function_arg_ir_type_or_none",
    "_gc_one_slot_borrowed_frame_map",
    "_gc_one_slot_frame_map",
    "_gc_release",
    "_gc_pin",
    "_gc_unpin",
    "_note_global_backed_value",
    "_value_available_at_insertion_point",
    "_gc_release_if_owned",
    "_note_never_gc_object",
    "_value_is_never_gc_object",
    "_gc_retain",
    "_get_floor_intrinsic",
    "_get_fmt_bool_false",
    "_get_fmt_bool_true",
    "_get_fmt_float",
    "_get_fmt_int",
    "_has_starred_unpack",
    "_init_l1_state",
    "_instruction_is_terminator",
    "_instruction_opname_text",
    "_int_expr_needs_exact_object_boundary",
    "_int_exprs_are_boxed",
    "_ir_module_symbol_target",
    "_ir_scaffold_class_symbol",
    "_ir_scaffold_enabled",
    "_ir_type_matches",
    "_is_extern_scaffold_import_module",
    "_is_object",
    "_is_scalar",
    "_is_starred_unpack",
    "_is_starred_unpack_expr",
    "_is_test_facade_import_module",
    "_join_reversed_strs",
    "_lambda_attr_chain",
    "_lambda_method_call",
    "_lambda_simple_subscript",
    "_load_cpython_builtin",
    "_map_type",
    "_mark_cpy_value",
    "_mark_owned_cpy_value",
    "_cpy_value_is_owned",
    "_forget_owned_cpy_value",
    "_release_cpy_callable_if_owned",
    "_guard_cpy_value_not_null",
    "_guard_cpy_status_not_negative",
    "_cpy_literal_cleanup_values",
    "_load_cpython_builtin_with_cleanup",
    "_require_supported_cpy_kw_mapping",
    "_leave_container_temp_root",
    "_make_cpy_operand_cleanup_block",
    "_emit_expr_with_cpy_operand_cleanup",
    "_begin_cpy_operand_evaluation",
    "_emit_checked_cpython_call_arg",
    "_bridge_cpy_arglist_operand",
    "_mark_owned_local_for_unpack_target",
    "_mark_owned_local_if_object",
    "_marshal_to_cpython",
    "_marshal_to_cpython_consuming_source",
    "_maybe_emit_builtin_type_method",
    "_maybe_emit_bytes_method_via_dyn",
    "_maybe_emit_discard_assignment",
    "_maybe_emit_exact_int_object",
    "_maybe_emit_valueclass_constructor_payload",
    "_maybe_emit_issubclass_builtin",
    "_maybe_emit_protocol_isinstance",
    "_maybe_register_class_alias_assign",
    "_method_arg_prefers_native_callable_value",
    "_method_returns_receiver",
    "_module_global_valueclass_payload_field_slot",
    "_module_global_needs_teardown",
    "_module_symbol_suffix",
    "_module_teardown_name",
    "_name_returns_native_builtin_callable_value",
    "_name_returns_owned_function_value",
    "_native_builtin_module_for_name",
    "_native_builtin_value_for_name",
    "_native_re_call_returns_owned_object",
    "_note_owned_object_value",
    "_value_is_owned_object",
    "_note_owned_dynamic_call_value",
    "_value_is_owned_dynamic_call",
    "_native_re_compile_alias_for_name",
    "_native_builtin_value_kind_for_expr",
    "_native_module_attr_global",
    "_native_module_expr_export_info",
    "_ordered_declare_extern_class_args",
    "_param_ir_and_bind_type",
    "_patch_fn_err_exit_gc_root_leave",
    "_position_at_entry_hoist_point",
    "_prescan_function_module_globals",
    "_ptr_to_cstr",
    "_push_try_err_block",
    "_raw_scaffold_object_rhs_is_owned",
    "_register_extern_scaffold_imports",
    "_register_native_builtin_import_from_aliases",
    "_register_native_builtin_module_alias",
    "_register_unsafe_scaffold_imports",
    "_release_context_label",
    "_release_existing_owned_local",
    "_release_expr_label",
    "_resolve_call_kwargs",
    "_resolve_class_alias",
    "_resolve_class_attr_mro",
    "_resolve_method_mro",
    "_resolve_relative_import",
    "_restore_try_err_block",
    "_return_expr_looks_cpython",
    "_rewrite_traceback_handler_bindings",
    "_should_box_python_ints",
    "_strict_no_libpython_import_fallback_enabled",
    "_strict_stub_user_function_with_cpy_fallback",
    "_storage_ir_type",
    "_store_entry_initializer",
    "_store_module_global_root_value",
    "_clear_module_global_valueclass_payload_roots",
    "_refresh_module_global_valueclass_payload_roots",
    "_subprocess_check_output_text_mode",
    "_threading_constructor_kind_for_expr",
    "_threading_list_elem_kind_for_expr",
    "_threading_list_elem_kind_for_type",
    "_to_double",
    "_to_int64",
    "_truthy",
    "_try_emit_native_file_stream_print",
    "_unpack_target_value_is_owned",
    "_unbox_scalar_attr_result",
    "_unsafe_intrinsic_for_name",
    "_unsafe_void_result",
    "_user_func_returns_cpython",
    "_utf8_byte_values",
    "_valueclass_field_info",
    "_valueclass_field_payload_ir_type",
    "_valueclass_payload_expr_type",
    "_valueclass_payload_pointer_field_paths",
    "_emit_entry_valueclass_payload_field_slot",
    "_ensure_valueclass_payload_gc_roots",
    "_emit_valueclass_payload_field_eq",
    "_emit_valueclass_payload_fields_eq",
    "_valueclass_payload_ir_type",
    "_is_valueclass_payload_type",
    "_virtual_thread_frame_map",
    "_weak_dict_constructor_kind_for_expr",
    "_weakref_call_expr_returns_owned_object",
    "_weakref_constructor_kind_for_expr",
    # Methods identified by the class_gen standalone fallback probe
    # as called through ``self.parent``.  See
    # ``scripts/regen_l1_codegen_static_methods.py``.  Run that script
    # after editing this tuple to refresh
    # ``pcc/py_frontend/codegen/_l1_codegen_static_methods.py``.
    "_abi_ir_type",
    "_attr_name_ptr",
    "_codegen_trace_dump",
    "_codegen_trace_push",
    "_codegen_trace_set_stmt_context",
    "_codegen_trace_span",
    "_emit_attribute_error_if_null",
    "_emit_direct_method_call",
    "_emit_async_native_func_value_adapter",
    "_active_handler_exception_for_current_function",
    "_emit_exception_frame",
    "_emit_generator_wrapper_function",
    "_emit_native_func_signature",
    "_emit_stmt",
    "_emit_thread_safepoint",
    "_native_re_class_compile_attr_string_value",
    "_pooled_cstr_ptr",
    "_zero_of",
)


def l1_codegen_lowering_host_contract():
    """Return the explicit host surface used by codegen mixins."""
    return (
        L1_CODEGEN_HOST_CLASS,
        L1_CODEGEN_HOST_ATTRS,
        L1_CODEGEN_HOST_METHODS,
    )


def per_module_probe_policy(module_name: str) -> str:
    """Return the semantic model for a per-module fallback probe."""
    if module_name.startswith("pcc.backend.self_backend_") or module_name in (
        "pcc.backend.arm64_asm_driver",
        "pcc.backend.arm64_encode",
        "pcc.backend.native_object",
        "pcc.backend.macho_spec",
    ):
        # These Modules execute as one closed-world compiler and increasingly
        # share typed kernel/value records across sibling files. A raw source
        # probe has no sibling export schemas and therefore invents dynamic
        # imports/calls that are absent from the production closure. They do
        # not use the L1CodeGen mixin host model. The owned encoding/format
        # siblings share those arena/relocation schemas across the same
        # native closure, even though their filenames omit self_backend_.
        return PROBE_POLICY_CLOSED_WORLD
    if module_name == "pcc.py_frontend.codegen.layer1":
        return PROBE_POLICY_CONTEXTUAL_MIXIN
    if module_name.startswith("pcc.py_frontend.codegen.native_"):
        return PROBE_POLICY_CONTEXTUAL_MIXIN
    if not module_name.startswith("pcc.py_frontend.codegen."):
        return PROBE_POLICY_STANDALONE
    prefix = "pcc.py_frontend.codegen."
    suffix = module_name[len(prefix) :]
    lowering_suffix = "_lowering"
    if (
        len(suffix) >= len(lowering_suffix)
        and suffix[len(suffix) - len(lowering_suffix) :] == lowering_suffix
    ):
        return PROBE_POLICY_CONTEXTUAL_MIXIN
    if suffix in (
        "core_helpers",
        "cpy_import_state",
        "cpy_return_analysis",
        "hoist_analysis",
        "hoist_boxing",
        "hoist_free_names",
        "hoist_predicates",
        "isinstance_lowering",
        "ir_decl_helpers",
        "ir_scaffold_lowering",
        "layer1_entrypoints",
        "layer1_init",
        "layer1_mixins",
        "typed_int_abi",
    ):
        return PROBE_POLICY_CONTEXTUAL_MIXIN
    return PROBE_POLICY_STANDALONE


def contextual_host_for_module(module_name: str) -> str:
    """Return the closed-world host class for a contextual probe."""
    if per_module_probe_policy(module_name) == PROBE_POLICY_CONTEXTUAL_MIXIN:
        return L1_CODEGEN_HOST_CLASS
    return ""


def contextual_per_module_modules(module_names) -> list[str]:
    out = []
    for module_name in module_names:
        if per_module_probe_policy(module_name) != PROBE_POLICY_STANDALONE:
            out.append(module_name)
    return out


__all__ = [
    "PROBE_POLICY_STANDALONE",
    "PROBE_POLICY_CONTEXTUAL_MIXIN",
    "PROBE_POLICY_CLOSED_WORLD",
    "L1_CODEGEN_HOST_CLASS",
    "L1_CODEGEN_HOST_ATTRS",
    "L1_CODEGEN_HOST_METHODS",
    "l1_codegen_lowering_host_contract",
    "per_module_probe_policy",
    "contextual_host_for_module",
    "contextual_per_module_modules",
]
