#!/usr/bin/env python3
"""scripts/freeze_c_parser_tables.py — P6C.5 α1 step 1.

Invokes PLY once (build time) and snapshots the LR tables + production
metadata into ``pcc/parse/c_parsetab.py`` as pure-data Python literals.

The self-host C parser (α1 driver, α1 step 3) reads this module
instead of importing PLY's yacc runtime.

Regenerate when grammar rules in ``pcc/parse/c_parser.py`` change::

    python scripts/freeze_c_parser_tables.py

Output:
  pcc/parse/c_parsetab.py — ACTION, GOTO, PRODUCTIONS as Python literals
  pcc/parse/c_parsetab_meta.py — grammar hash + production list

The companion hash check in CI will fail if someone edits grammar
rules without regenerating the table.
"""
from __future__ import annotations

import hashlib
import sys
import textwrap
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))


def _grammar_hash() -> str:
    """Hash the p_* method bodies so CI can detect "grammar edited
    without freeze regeneration" situations."""
    import ast
    import inspect
    from pcc.parse.c_parser import CParser  # noqa: E402

    src_parts: list[str] = []
    for name in sorted(dir(CParser)):
        if not name.startswith("p_"):
            continue
        fn = getattr(CParser, name)
        if not callable(fn):
            continue
        try:
            src = inspect.getsource(fn)
        except (OSError, TypeError):
            continue
        src_parts.append(src)
    digest = hashlib.sha256("\n---\n".join(src_parts).encode("utf-8")).hexdigest()
    return digest


def _action_name_for(prod) -> str:
    """Return the logical action name for a production.

    - Regular grammar rules: ``p_binary_expression_1`` etc.
    - PLY-synthesised ``<rule>_opt`` rules: ``_opt_rule`` (they all
      do the same ``stack[-1]`` identity action).
    - Augmented start rule ``S' -> translation_unit``: ``_accept``.
    """
    if prod.callable is None:
        return "_accept"
    qn = prod.callable.__qualname__
    if "_create_opt_rule" in qn or qn.endswith("optrule"):
        return "_opt_rule"
    return prod.callable.__name__


def main() -> int:
    from pcc.parse.c_parser import CParser  # noqa: E402

    parser = CParser()
    yp = parser.cparser

    # Productions table — one entry per LR production
    prod_entries: list[tuple[str, int, str, str]] = []
    # (lhs, rhs_len, action_name, str_form)
    for i, prod in enumerate(yp.productions):
        prod_entries.append(
            (prod.name, prod.len, _action_name_for(prod), prod.str)
        )

    # ACTION: state -> token -> signed int
    #    > 0: shift to new state
    #    < 0: reduce by production -action
    #    = 0: accept
    action = {
        s: {tok: int(act) for tok, act in row.items()}
        for s, row in yp.action.items()
    }
    # GOTO: state -> nonterminal -> state
    goto = {
        s: {nt: int(g) for nt, g in row.items()}
        for s, row in yp.goto.items()
    }

    grammar_digest = _grammar_hash()

    out_path = REPO / "pcc" / "parse" / "c_parsetab.py"
    body = _emit_module(prod_entries, action, goto, grammar_digest)
    out_path.write_text(body)

    print(f"wrote {out_path.relative_to(REPO)}")
    print(f"  productions: {len(prod_entries)}")
    print(f"  ACTION states: {len(action)}")
    print(f"  GOTO states: {len(goto)}")
    print(f"  grammar sha256: {grammar_digest[:16]}...")
    print(f"  file size: {out_path.stat().st_size / 1024:.1f} KB")
    return 0


def _emit_module(
    productions: list[tuple[str, int, str, str]],
    action: dict[int, dict[str, int]],
    goto: dict[int, dict[str, int]],
    grammar_digest: str,
) -> str:
    """Render the frozen-table module as a Python source string."""
    header = textwrap.dedent('''\
        """pcc.parse.c_parsetab — FROZEN C parser LR tables.

        AUTO-GENERATED by ``scripts/freeze_c_parser_tables.py`` from the
        grammar in ``pcc.parse.c_parser``. Do NOT hand-edit. Regenerate
        via the script if grammar rules change.

        Consumed by ``pcc.parse.c_parse_driver`` (P6C.5 α1 step 3).
        No PLY import at load time — this is pure static data.
        """
        from __future__ import annotations

        # SHA-256 of concatenated p_* method sources from
        # pcc/parse/c_parser.py at generation time. CI cross-checks this
        # against the live grammar to detect stale tables.
    ''')
    parts: list[str] = [header]
    parts.append(f'GRAMMAR_SHA256 = {grammar_digest!r}\n\n')

    # PRODUCTIONS tuple
    parts.append("# One entry per LR production:\n")
    parts.append("#   (lhs_nonterminal, rhs_len, action_name, human_readable_form)\n")
    parts.append("# action_name values:\n")
    parts.append("#   - ``p_<rule>``: call pcc.parse.c_parser_actions.<rule>\n")
    parts.append("#   - ``_opt_rule``: identity (synthesised ``<x>_opt`` rules)\n")
    parts.append("#   - ``_accept``: augmented start (terminate parse)\n")
    parts.append("PRODUCTIONS: tuple = (\n")
    for lhs, rlen, action_name, str_form in productions:
        parts.append(
            f"    ({lhs!r}, {rlen}, {action_name!r}, {str_form!r}),\n"
        )
    parts.append(")\n\n")

    # ACTION dict — large but data-only
    parts.append("# ACTION: state -> {token: signed_int}\n")
    parts.append("#   > 0: shift to state N\n")
    parts.append("#   < 0: reduce by production -N\n")
    parts.append("#   = 0: accept (augmented start)\n")
    parts.append("ACTION: dict = {\n")
    for s in sorted(action):
        row = action[s]
        # Emit a compact one-line dict; sort keys for determinism.
        items = ", ".join(f"{tok!r}: {a}" for tok, a in sorted(row.items()))
        parts.append(f"    {s}: {{{items}}},\n")
    parts.append("}\n\n")

    parts.append("# GOTO: state -> {nonterminal: next_state}\n")
    parts.append("GOTO: dict = {\n")
    for s in sorted(goto):
        row = goto[s]
        items = ", ".join(f"{nt!r}: {g}" for nt, g in sorted(row.items()))
        parts.append(f"    {s}: {{{items}}},\n")
    parts.append("}\n")

    return "".join(parts)


if __name__ == "__main__":
    raise SystemExit(main())
