#!/usr/bin/env python3
"""Generate compiler constants and the public owned-FILE layout header."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys


REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from pcc.py_runtime.freestanding_abi_spec import ABI_SPEC, STDIO_FILE_FIELDS


PY_OUTPUT = (
    REPO_ROOT / "pcc" / "py_frontend" / "codegen" / "freestanding_abi_constants.py"
)
HEADER_OUTPUT = REPO_ROOT / "pcc" / "py_runtime" / "include" / "pcc_stdio_abi.h"


def render_python() -> str:
    lines = [
        '"""Generated freestanding ABI constants. Do not edit by hand."""',
        "",
        "ABI_CONSTANTS: dict[str, int] = {",
    ]
    for name in sorted(ABI_SPEC):
        lines.append(f"    {name!r}: {ABI_SPEC[name]},")
    lines.extend(
        (
            "}",
            "",
            "# Compiler-facing aliases for the generated public object-tag ABI.",
            "# Literal assignments keep self-hosted module initialization static;",
            "# both this table and these aliases are emitted from the same ABI spec.",
        )
    )
    for name in sorted(ABI_SPEC):
        prefix = "object.type."
        if name.startswith(prefix):
            alias = "PY_TYPE_" + name[len(prefix) :].upper()
            lines.append(f"{alias} = {ABI_SPEC[name]}")
    lines.append("")
    return "\n".join(lines)


def render_header() -> str:
    size = ABI_SPEC["stdio.file.size"]
    lines = [
        "/* Generated by scripts/gen_freestanding_stdio_abi.py. */",
        "#ifndef PCC_STDIO_ABI_H",
        "#define PCC_STDIO_ABI_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "typedef struct PccOwnedFile {",
    ]
    for field, c_type in STDIO_FILE_FIELDS:
        lines.append(f"    {c_type} {field};")
    lines.extend(
        (
            "} PccOwnedFile;",
            "",
            f"#define PCC_STDIO_FILE_MAGIC {ABI_SPEC['stdio.file.magic']}ULL",
            f"#define PCC_STDIO_FILE_SIZE {size}",
            f"#define PCC_STDIO_FLAG_READABLE {ABI_SPEC['stdio.flag.readable']}ULL",
            f"#define PCC_STDIO_FLAG_WRITABLE {ABI_SPEC['stdio.flag.writable']}ULL",
            f"#define PCC_STDIO_FLAG_ERROR {ABI_SPEC['stdio.flag.error']}ULL",
            f"#define PCC_STDIO_FLAG_EOF {ABI_SPEC['stdio.flag.eof']}ULL",
            f"#define PCC_STDIO_FLAG_STANDARD {ABI_SPEC['stdio.flag.standard']}ULL",
            f"#define PCC_STDIO_FLAG_APPEND {ABI_SPEC['stdio.flag.append']}ULL",
            "",
        )
    )
    for field, _c_type in STDIO_FILE_FIELDS:
        offset = ABI_SPEC[f"stdio.file.{field}_offset"]
        lines.append(
            f"_Static_assert(offsetof(PccOwnedFile, {field}) == {offset}, "
            f'"PccOwnedFile.{field} ABI");'
        )
    lines.extend(
        (
            f'_Static_assert(sizeof(PccOwnedFile) == {size}, "PccOwnedFile size ABI");',
            "",
            "#endif",
            "",
        )
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = {
        PY_OUTPUT: render_python(),
        HEADER_OUTPUT: render_header(),
    }
    if args.check:
        stale = [path for path, expected in outputs.items() if not path.exists() or path.read_text(encoding="utf-8") != expected]
        if stale:
            for path in stale:
                print(f"stale generated ABI output: {path.relative_to(REPO_ROOT)}")
            return 1
        print("freestanding stdio ABI outputs match the single spec")
        return 0
    for path, rendered in outputs.items():
        path.write_text(rendered, encoding="utf-8")
        print(f"wrote {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
