#!/usr/bin/env python3
"""Stage1 closure probe (#212).

Force-recurse the same-package absolute-import walker over
``pcc/__main__.py`` and try to compile the entire 51-file closure as
one multi-file unit. Capture per-module failures and IR fallback
density. Read-only: does not modify pipeline defaults.

Output:
- /tmp/stage1_closure_probe.ll (combined IR if compile succeeded)
- docs/plans/stage1-closure-probe.md (report)
"""
from __future__ import annotations

import os
import sys
import traceback


def _set_env_defaults() -> None:
    os.environ.setdefault("PCC_PYTHON_LIBPYTHON", "auto")


def _try_per_module_lower(srcs: list[str], mods: list[str]):
    """Compile each module independently to surface codegen failures
    without aborting on the first error."""
    from pcc.py_frontend import pipeline as _pipeline
    from pcc.py_frontend import type_infer as _type_infer
    from pcc.py_frontend.codegen import layer1 as _layer1
    from pcc.parse.py_lift import parse_and_lift

    results = []
    for src, mod in zip(srcs, mods):
        ok = True
        stage = "parse"
        err = None
        try:
            with open(src, "r", encoding="utf-8") as f:
                source = f.read()
            ast_mod = parse_and_lift(source, src, mod)
            stage = "needs_libpython"
            needs = _pipeline._module_needs_libpython(ast_mod, native_modules=mods)
            stage = "type_infer"
            typed = _type_infer.infer_module(ast_mod)
            stage = "codegen"
            cg = _layer1.L1CodeGen(typed, emit_cpy_main_exitcode=False)
            ir = cg.generate(typed)
            ir_text = str(ir)
            stage = "done"
            cpy_calls = _count_py_cpy_calls(ir_text)
        except Exception as e:
            ok = False
            err = f"{type(e).__name__}: {e}"
            cpy_calls = 0
            needs = None
        results.append({
            "module": mod,
            "src": src,
            "ok": ok,
            "fail_stage": None if ok else stage,
            "error": err,
            "needs_libpython_ast": needs,
            "py_cpy_calls": cpy_calls,
        })
    return results


def _count_py_cpy_calls(ir_text: str) -> int:
    import re
    return len(re.findall(r"\bcall [^\n]*@py_cpy_", ir_text))


def _try_full_multi_compile(srcs: list[str], mods: list[str]) -> tuple[bool, str, str]:
    """Try the actual compile_python_multi over the closure with
    libpython=auto. Return (ok, ir_text_or_empty, error)."""
    from pcc.py_frontend.pipeline import compile_python_multi
    out_path = "/tmp/stage1_closure_probe.ll"
    try:
        compile_python_multi(
            srcs,
            out_path,
            verbose=False,
            emit_llvm_only=True,
            entry_module=mods[0],
            module_names=mods,
            libpython_mode="auto",
            backend="llvm",
        )
        if os.path.exists(out_path):
            with open(out_path, "r", encoding="utf-8") as f:
                ir_text = f.read()
            return True, ir_text, ""
        return False, "", "no IR produced"
    except Exception as e:
        return False, "", f"{type(e).__name__}: {e}\n{traceback.format_exc()}"


def _classify_top_fallbacks(ir_text: str) -> list[tuple[int, str]]:
    import re
    counts = {}
    for m in re.finditer(r"\bcall [^\n]*@(py_cpy_[a-z0-9_]+)", ir_text):
        name = m.group(1)
        counts[name] = counts.get(name, 0) + 1
    return sorted(counts.items(), key=lambda kv: -kv[1])


def _categorize_error(err: str) -> str:
    if not err:
        return "ok"
    s = err.lower()
    if "notimplementederror" in s:
        if "lambda" in s:
            return "codegen.lambda"
        if "kwarg" in s or "keyword" in s:
            return "codegen.kwargs"
        if "comprehension" in s or "_list_comp" in s:
            return "codegen.comprehension"
        if "decorator" in s:
            return "codegen.decorator"
        return "codegen.other"
    if "typeinferenceerror" in s or "type_infer" in s:
        return "type_infer"
    if "pypipelineerror" in s:
        return "pipeline"
    if "syntaxerror" in s or "parse" in s:
        return "parse"
    return "other"


def _write_report(srcs, mods, per_mod, multi_ok, multi_err, top_fb, total_fb, ir_lines):
    report = []
    report.append("# Stage1 Closure Probe Report\n")
    report.append("Generated by `scripts/probe_stage1_closure.py` (#212).\n")
    report.append("")
    mode = os.environ.get("PCC_PROBE_CLOSURE", "tight")
    walker_label = (
        "max — include_same_package_absolute=True, recurse=True"
        if mode == "max"
        else "tight — entry one-hop same-pkg-absolute enqueued + relative recursion"
    )
    report.append("## Summary\n")
    report.append(f"- Closure walker: {walker_label}")
    report.append(f"- Closure size: **{len(srcs)} files**")
    ok_count = sum(1 for r in per_mod if r["ok"])
    report.append(f"- Per-module independent codegen pass: **{ok_count} / {len(per_mod)}**")
    report.append(f"- Full multi-file compile: **{'OK' if multi_ok else 'FAIL'}**")
    if multi_ok:
        report.append(f"- Combined IR lines: {ir_lines}")
        report.append(f"- `py_cpy_*` calls in combined IR: **{total_fb}**")
    report.append("")
    if not multi_ok:
        report.append("### Multi-file failure\n")
        report.append("```\n" + multi_err.strip() + "\n```\n")
    if top_fb:
        report.append("## Top fallback symbols (combined IR)\n")
        report.append("| count | symbol |")
        report.append("|---:|---|")
        for sym, n in [(s, c) for s, c in top_fb][:25]:
            # sym/n swapped above accidentally — fix:
            pass
        for sym, n in top_fb[:25]:
            report.append(f"| {n} | `{sym}` |")
        report.append("")
    fails = [r for r in per_mod if not r["ok"]]
    if fails:
        report.append("## Per-module failures (independent codegen)\n")
        cat_groups = {}
        for r in fails:
            cat = _categorize_error(r["error"])
            cat_groups.setdefault(cat, []).append(r)
        report.append(f"Total failing modules: **{len(fails)}**\n")
        for cat, rs in sorted(cat_groups.items()):
            report.append(f"### Category: `{cat}` ({len(rs)} module(s))\n")
            for r in rs:
                err_short = (r["error"] or "").splitlines()[0][:200]
                report.append(f"- **{r['module']}** ({r['fail_stage']}): {err_short}")
            report.append("")
    needs_lp = [r for r in per_mod if r["ok"] and r["needs_libpython_ast"]]
    if needs_lp:
        report.append("## Modules whose AST needs libpython (import-driven)\n")
        for r in needs_lp:
            report.append(f"- {r['module']}")
        report.append("")
    # Conclusion section — written into both tight and max reports so
    # readers don't need to cross-reference.
    report.append("## Interpretation\n")
    report.append(
        "Stage1 default behaviour today closes the import graph at "
        "`pcc.__main__` + `pcc.cli_bootstrap` (2 files, ~25 fallbacks). "
        "Those 25 fallbacks are the IR-visible cost of `cli_bootstrap` "
        "calling `compile_python(...)` via dynamic dispatch; the rest "
        "of the frontend is not in the native compile graph at all and "
        "runs as CPython-interpreted code linked through the same "
        "`libpython` that backs the fallback shims.\n"
    )
    report.append(
        "Pulling more files into the native compile graph (this probe) "
        "exposes the `py_cpy_*` density that already lives inside "
        "`layer1.py`, `runtime_abi.py`, and `pipeline.py` — it does "
        "**not** remove libpython, it just shifts who is using it. "
        "Pure-native frontend self-compile is therefore not a walker "
        "default flip; it is a long-running effort to remove dynamic "
        "Python idioms from those hot files.\n"
    )
    report.append(
        "Tracking goal: `tight` total fallback count is the headline "
        "metric to drive down. Re-run this probe periodically; commit "
        "the report so deltas are visible in git history.\n"
    )
    if per_mod and any(r["py_cpy_calls"] for r in per_mod):
        report.append("## Per-module `py_cpy_*` density (independent codegen)\n")
        report.append("| module | py_cpy calls |")
        report.append("|---|---:|")
        for r in sorted(per_mod, key=lambda r: -r["py_cpy_calls"]):
            if r["py_cpy_calls"] > 0:
                report.append(f"| {r['module']} | {r['py_cpy_calls']} |")
        report.append("")
    return "\n".join(report)


def _tightened_closure(entry_src: str) -> tuple[list[str], list[str]]:
    """Walker that enqueues entry's same-package absolute one-hops AND
    follows relative imports from them, but does NOT keep recursing into
    same-package absolute imports beyond the entry. Yields the
    'frontend core' closure rather than the maximal 51-file one."""
    from pcc.py_frontend.pipeline import (
        _package_import_targets,
        _module_root_from_src,
        _module_name_from_src,
    )
    entry_src = os.path.abspath(entry_src)
    entry_mod = _module_name_from_src(entry_src)
    root = _module_root_from_src(entry_src, entry_mod)
    ordered = [entry_src]
    mods = [entry_mod]
    seen = {entry_mod: entry_src}
    queue = [(entry_src, entry_mod)]
    for ts, tm in _package_import_targets(
        entry_src, entry_mod, root_dir=root,
        include_relative=False, include_same_package_absolute=True,
    ):
        if tm in seen:
            continue
        ts = os.path.abspath(ts)
        seen[tm] = ts
        ordered.append(ts); mods.append(tm); queue.append((ts, tm))
    while queue:
        s, m = queue.pop(0)
        for ts, tm in _package_import_targets(
            s, m, root_dir=root,
            include_relative=True, include_same_package_absolute=False,
        ):
            if tm in seen:
                continue
            ts = os.path.abspath(ts)
            seen[tm] = ts
            ordered.append(ts); mods.append(tm); queue.append((ts, tm))
    return ordered, mods


def main() -> int:
    _set_env_defaults()
    sys.path.insert(0, os.path.abspath(os.path.dirname(os.path.dirname(__file__))))
    from pcc.py_frontend.pipeline import _collect_relative_module_closure

    entry = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "..", "pcc", "__main__.py")
    )
    mode = os.environ.get("PCC_PROBE_CLOSURE", "tight")
    if mode == "max":
        srcs, mods = _collect_relative_module_closure(
            entry,
            include_same_package_absolute=True,
            recurse_same_package_absolute=True,
        )
    else:
        srcs, mods = _tightened_closure(entry)
    print(f"closure ({mode}): {len(srcs)} files", flush=True)

    print("[1/3] independent per-module codegen...", flush=True)
    per_mod = _try_per_module_lower(srcs, mods)
    ok = sum(1 for r in per_mod if r["ok"])
    print(f"  ok: {ok}/{len(per_mod)}", flush=True)

    print("[2/3] full multi-file compile...", flush=True)
    multi_ok, ir_text, multi_err = _try_full_multi_compile(srcs, mods)
    print(f"  multi: {'OK' if multi_ok else 'FAIL'}", flush=True)

    print("[3/3] writing report...", flush=True)
    if multi_ok:
        top_fb = _classify_top_fallbacks(ir_text)
        total_fb = sum(n for _, n in top_fb)
        ir_lines = ir_text.count("\n")
    else:
        top_fb = []
        total_fb = 0
        ir_lines = 0

    report = _write_report(srcs, mods, per_mod, multi_ok, multi_err,
                           top_fb, total_fb, ir_lines)
    suffix = "" if mode == "tight" else f"-{mode}"
    out_md = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "..",
                     "docs", "plans",
                     f"stage1-closure-probe{suffix}.md")
    )
    with open(out_md, "w", encoding="utf-8") as f:
        f.write(report)
    print(f"wrote {out_md}", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
