"""Host-subprocess source payloads used by the Python frontend pipeline.

These strings are part of the bootstrap contract. Keep their contents
behavior-identical while the thin pipeline facade continues to re-export
the historical private names.
"""

from __future__ import annotations

_SELF_BACKEND_HOST_CODE = (
    "import sys\n"
    "import os\n"
    "pcc_source_root = sys.argv[1]\n"
    "if pcc_source_root and pcc_source_root not in sys.path:\n"
    "    sys.path.insert(0, pcc_source_root)\n"
    "if pcc_source_root:\n"
    "    os.environ.setdefault('PCC_SOURCE_ROOT', pcc_source_root)\n"
    "    os.environ.setdefault('PCC_REPO_ROOT', pcc_source_root)\n"
    "from pcc.backend.self_backend_dispatch import emit_self_asm, "
    "self_backend_target_identity\n"
    "from pcc.backend.self_backend_parse import "
    "parse_self_backend_target_triple\n"
    "path = sys.argv[2]\n"
    "with open(path, 'r', encoding='utf-8') as f:\n"
    "    text = f.read()\n"
    "triple = parse_self_backend_target_triple(text)\n"
    "sys.stdout.write(self_backend_target_identity(triple) + '\\n')\n"
    "sys.stdout.write(emit_self_asm(text))\n"
)

_COMPILER_CACHE_RETENTION_HOST_CODE = (
    "import sys\n"
    "try:\n"
    "    pcc_source_root = sys.argv[1]\n"
    "    if pcc_source_root and pcc_source_root not in sys.path:\n"
    "        sys.path.insert(0, pcc_source_root)\n"
    "    from pcc.tools.compiler_cache_retention import maintain_cache\n"
    "    root = sys.argv[2]\n"
    "    protected = sys.argv[3:]\n"
    "    report = maintain_cache(root, automatic=True, protected_paths=protected)\n"
    "    reclaimed = int(report.get('reclaimed_bytes', 0) or 0)\n"
    "    failures = int(report.get('quarantine_failures', 0) or 0)\n"
    "    pending = int(report.get('quarantine_pending', 0) or 0)\n"
    "    if reclaimed or failures or pending:\n"
    "        sys.stderr.write('pcc compiler cache retention: reclaimed=' "
    "+ str(reclaimed) + ' bytes_after=' "
    "+ str(report.get('bytes_after', 0)) + ' failures=' + str(failures) "
    "+ ' pending=' + str(pending) + '\\n')\n"
    "except BaseException as exc:\n"
    "    message = str(exc).replace('\\n', ' ')[:200]\n"
    "    sys.stderr.write('pcc compiler cache retention skipped: ' "
    "+ type(exc).__name__ + (': ' + message if message else '') + '\\n')\n"
    "    raise SystemExit(2)\n"
)
_SELF_BACKEND_HOST_MANY_CODE = (
    "import glob\n"
    "import hashlib\n"
    "import json\n"
    "import multiprocessing as mp\n"
    "import os\n"
    "import platform\n"
    "import shutil\n"
    "import subprocess\n"
    "import sys\n"
    "import time\n"
    "pcc_source_root = sys.argv[1]\n"
    "if pcc_source_root and pcc_source_root not in sys.path:\n"
    "    sys.path.insert(0, pcc_source_root)\n"
    "if pcc_source_root:\n"
    "    os.environ.setdefault('PCC_SOURCE_ROOT', pcc_source_root)\n"
    "    os.environ.setdefault('PCC_REPO_ROOT', pcc_source_root)\n"
    "from pcc.backend.self_backend_dispatch import emit_self_asm, "
    "self_backend_target_identity\n"
    "from pcc.backend.self_backend_parse import "
    "parse_self_backend_target_triple\n"
    "\n"
    "_OBJECT_CACHE_VERSION = 'pcc.self-backend-object-cache.v2'\n"
    "_OBJECT_CACHE_ENV = 'PCC_SELF_BACKEND_OBJECT_CACHE'\n"
    "_OBJECT_CACHE_DIR_ENV = 'PCC_SELF_BACKEND_OBJECT_CACHE_DIR'\n"
    "_OBJECT_CACHE_IDENTITY = None\n"
    "\n"
    "def _object_cache_enabled():\n"
    "    value = str(os.environ.get(_OBJECT_CACHE_ENV, '') or '').strip().lower()\n"
    "    return value not in ('0', 'false', 'no', 'off', 'disable', 'disabled')\n"
    "\n"
    "def _object_cache_dir():\n"
    "    override = str(os.environ.get(_OBJECT_CACHE_DIR_ENV, '') or '').strip()\n"
    "    if override:\n"
    "        return os.path.expanduser(override)\n"
    "    xdg_cache_home = str(os.environ.get('XDG_CACHE_HOME', '') or '').strip()\n"
    "    if xdg_cache_home:\n"
    "        base = xdg_cache_home\n"
    "    else:\n"
    "        base = os.path.join(os.path.expanduser('~'), '.cache')\n"
    "    return os.path.join(base, 'pcc', 'self-backend-object-cache')\n"
    "\n"
    "def _hash_file_into(h, path):\n"
    "    try:\n"
    "        with open(path, 'rb') as f:\n"
    "            while True:\n"
    "                chunk = f.read(1024 * 1024)\n"
    "                if not chunk:\n"
    "                    break\n"
    "                h.update(chunk)\n"
    "    except OSError:\n"
    "        h.update(b'<unreadable>')\n"
    "\n"
    "def _object_cache_identity():\n"
    "    global _OBJECT_CACHE_IDENTITY\n"
    "    if _OBJECT_CACHE_IDENTITY is not None:\n"
    "        return _OBJECT_CACHE_IDENTITY\n"
    "    h = hashlib.sha256()\n"
    "    h.update(_OBJECT_CACHE_VERSION.encode('utf-8'))\n"
    "    h.update(b'\\0')\n"
    "    h.update(sys.platform.encode('utf-8'))\n"
    "    h.update(b'\\0')\n"
    "    h.update((platform.machine() or '').encode('utf-8'))\n"
    "    h.update(b'\\0')\n"
    "    for name in ('PCC_SELF_TARGET_PASSES', 'PCC_SELF_TARGET_PASS_TRANSPORT'):\n"
    "        h.update(name.encode('utf-8'))\n"
    "        h.update(b'=')\n"
    "        h.update(str(os.environ.get(name, '') or '').encode('utf-8'))\n"
    "        h.update(b'\\0')\n"
    "    try:\n"
    "        import pcc.backend.self_backend_dispatch as _dispatch_module\n"
    "        backend_dir = os.path.dirname(os.path.abspath(_dispatch_module.__file__))\n"
    "        backend_files = [path for path in "
    "sorted(glob.glob(os.path.join(backend_dir, 'self_backend*.py'))) "
    "if os.path.basename(path) != 'self_backend_cache_identity.py']\n"
    "    except Exception:\n"
    "        backend_files = []\n"
    "    for path in backend_files:\n"
    "        h.update(os.path.basename(path).encode('utf-8'))\n"
    "        h.update(b'\\0')\n"
    "        _hash_file_into(h, path)\n"
    "        h.update(b'\\0')\n"
    "    _OBJECT_CACHE_IDENTITY = h.hexdigest()\n"
    "    return _OBJECT_CACHE_IDENTITY\n"
    "\n"
    "def _object_cache_path(text, target_id):\n"
    "    if not _object_cache_enabled():\n"
    "        return None\n"
    "    h = hashlib.sha256()\n"
    "    h.update(_object_cache_identity().encode('utf-8'))\n"
    "    h.update(b'\\0')\n"
    "    h.update(str(cc).encode('utf-8'))\n"
    "    h.update(b'\\0')\n"
    "    h.update(str(target_id).encode('utf-8'))\n"
    "    h.update(b'\\0')\n"
    "    h.update(('internal-asm' if internal_link else 'macho').encode('utf-8'))\n"
    "    h.update(b'\\0')\n"
    "    h.update(text.encode('utf-8'))\n"
    "    digest = h.hexdigest()\n"
    "    suffix = '.s' if internal_link else '.o'\n"
    "    return os.path.join(_object_cache_dir(), digest[:2], digest + suffix)\n"
    "\n"
    "def _cache_lease(cache_path, suffix):\n"
    "    if not cache_path:\n"
    "        return ''\n"
    "    os.makedirs(os.path.dirname(cache_path), exist_ok=True)\n"
    "    eviction = cache_path + '.pcc-evict'\n"
    "    if os.path.exists(eviction):\n"
    "        return ''\n"
    "    lease = cache_path + '.pcc-lease.' + str(os.getpid()) + '.' + suffix\n"
    "    try:\n"
    "        fd = os.open(lease, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)\n"
    "        with os.fdopen(fd, 'w', encoding='utf-8') as stream:\n"
    "            json.dump({'pid': os.getpid(), 'created_ns': time.time_ns()}, stream, sort_keys=True, separators=(',', ':'))\n"
    "            stream.write('\\n')\n"
    "        if os.path.exists(eviction):\n"
    "            os.unlink(lease)\n"
    "            return ''\n"
    "        return lease\n"
    "    except OSError:\n"
    "        return ''\n"
    "\n"
    "def _cache_touch(cache_path, suffix):\n"
    "    if not os.path.exists(cache_path):\n"
    "        return\n"
    "    marker = cache_path + '.pcc-last-used'\n"
    "    temporary = marker + '.tmp.' + str(os.getpid()) + '.' + suffix\n"
    "    try:\n"
    "        with open(temporary, 'w', encoding='ascii') as stream:\n"
    "            stream.write(str(time.time_ns()) + '\\n')\n"
    "        os.replace(temporary, marker)\n"
    "        if not os.path.exists(cache_path):\n"
    "            os.unlink(marker)\n"
    "    except OSError:\n"
    "        try:\n"
    "            os.unlink(temporary)\n"
    "        except OSError:\n"
    "            pass\n"
    "\n"
    "def _populate_object_cache(cache_path, obj_path):\n"
    "    if not cache_path:\n"
    "        return\n"
    "    lease = _cache_lease(cache_path, 'publish')\n"
    "    if not lease:\n"
    "        return\n"
    "    tmp_path = ''\n"
    "    try:\n"
    "        os.makedirs(os.path.dirname(cache_path), exist_ok=True)\n"
    "        tmp_path = cache_path + '.' + str(os.getpid()) + '.tmp'\n"
    "        shutil.copyfile(obj_path, tmp_path)\n"
    "        os.replace(tmp_path, cache_path)\n"
    "        _cache_touch(cache_path, 'publish')\n"
    "    except OSError:\n"
    "        pass\n"
    "    finally:\n"
    "        for leftover in (tmp_path, lease):\n"
    "            try:\n"
    "                os.unlink(leftover)\n"
    "            except OSError:\n"
    "                pass\n"
    "\n"
    "def _host_target_triple_for_self_backend():\n"
    "    if sys.platform == 'darwin':\n"
    "        machine = platform.machine() or 'unknown'\n"
    "        if machine == 'arm64':\n"
    "            machine = 'aarch64'\n"
    "        return machine + '-apple-darwin'\n"
    "    if sys.platform.startswith('linux'):\n"
    "        machine = platform.machine() or 'unknown'\n"
    "        if machine in ('amd64', 'x64'):\n"
    "            machine = 'x86_64'\n"
    "        return machine + '-unknown-linux-gnu'\n"
    "    return 'unknown-unknown-unknown'\n"
    "\n"
    "def _self_backend_ir_text(ir_text):\n"
    "    ir_text = str(ir_text)\n"
    "    placeholder = 'target triple = \"unknown-unknown-unknown\"'\n"
    "    header = ir_text[:4096]\n"
    "    idx = header.find(placeholder)\n"
    "    if idx >= 0:\n"
    "        replacement = 'target triple = \"' + "
    "_host_target_triple_for_self_backend() + '\"'\n"
    "        return ir_text[:idx] + replacement + ir_text[idx + len(placeholder):]\n"
    "    if 'target triple = \"' not in header:\n"
    "        return 'target triple = \"' + _host_target_triple_for_self_backend() "
    "+ '\"\\n' + ir_text\n"
    "    return ir_text\n"
    "\n"
    "def _emit_one(item):\n"
    "    idx, path = item\n"
    "    with open(path, 'r', encoding='utf-8') as f:\n"
    "        text = _self_backend_ir_text(f.read())\n"
    "    triple = parse_self_backend_target_triple(text)\n"
    "    target_id = self_backend_target_identity(triple)\n"
    "    asm_path = path + '.s'\n"
    "    obj_path = asm_path if internal_link else path + '.o'\n"
    "    cache_path = _object_cache_path(text, target_id)\n"
    "    if cache_path and os.path.isfile(cache_path):\n"
    "        lease = _cache_lease(cache_path, 'read.' + str(idx))\n"
    "        if lease:\n"
    "            try:\n"
    "                shutil.copyfile(cache_path, obj_path)\n"
    "                _cache_touch(cache_path, 'read.' + str(idx))\n"
    "                return idx, target_id, obj_path, 0, 0, len(text), 'hit', cache_path\n"
    "            except OSError:\n"
    "                pass\n"
    "            finally:\n"
    "                try:\n"
    "                    os.unlink(lease)\n"
    "                except OSError:\n"
    "                    pass\n"
    "    cache_status = 'miss' if cache_path else 'off'\n"
    "    t0 = time.monotonic()\n"
    "    asm_text = emit_self_asm(text)\n"
    "    emit_ms = int((time.monotonic() - t0) * 1000)\n"
    "    with open(asm_path, 'w', encoding='utf-8') as f:\n"
    "        f.write(asm_text)\n"
    "    cc_ms = 0\n"
    "    if not internal_link:\n"
    "        t1 = time.monotonic()\n"
    "        subprocess.run([cc, '-c', asm_path, '-o', obj_path], check=True)\n"
    "        cc_ms = int((time.monotonic() - t1) * 1000)\n"
    "    _populate_object_cache(cache_path, obj_path)\n"
    "    return idx, target_id, obj_path, emit_ms, cc_ms, len(text), cache_status, (cache_path or '')\n"
    "\n"
    "jobs = int(sys.argv[2])\n"
    "cc = sys.argv[3]\n"
    "split_large_modules = sys.argv[4] == '1'\n"
    "result_path = sys.argv[5]\n"
    "internal_link = sys.argv[6] == '1'\n"
    "paths = list(sys.argv[7:])\n"
    "if split_large_modules:\n"
    "    _pipeline = __import__('pcc.py_frontend.pipeline', "
    "fromlist=['_split_self_backend_large_ir_modules'])\n"
    "    _split_self_backend_large_ir_modules = getattr(_pipeline, "
    "'_split_self_backend_large_ir_modules')\n"
    "    texts = []\n"
    "    for path in paths:\n"
    "        with open(path, 'r', encoding='utf-8') as f:\n"
    "            texts.append(_self_backend_ir_text(f.read()))\n"
    "    texts = _split_self_backend_large_ir_modules(texts)\n"
    "    expanded_paths = []\n"
    "    result_dir = os.path.dirname(result_path)\n"
    "    for idx, text in enumerate(texts):\n"
    "        path = os.path.join(result_dir, 'self_backend_expanded_' + "
    "str(idx) + '.ll')\n"
    "        with open(path, 'w', encoding='utf-8') as f:\n"
    "            f.write(text)\n"
    "        expanded_paths.append(path)\n"
    "    items = list(enumerate(expanded_paths))\n"
    "else:\n"
    "    items = list(enumerate(paths))\n"
    "if jobs <= 0:\n"
    "    jobs = os.cpu_count() or 1\n"
    "jobs = max(1, min(len(items), jobs))\n"
    "if jobs > 1 and len(items) > 1:\n"
    "    try:\n"
    "        mp.set_start_method('fork')\n"
    "    except (RuntimeError, ValueError):\n"
    "        pass\n"
    "    if mp.get_start_method(allow_none=True) == 'fork':\n"
    "        with mp.Pool(processes=jobs) as pool:\n"
    "            results = pool.map(_emit_one, items, chunksize=1)\n"
    "    else:\n"
    "        results = [_emit_one(item) for item in items]\n"
    "else:\n"
    "    results = [_emit_one(item) for item in items]\n"
    "try:\n"
    "    if _object_cache_enabled():\n"
    "        from pcc.tools.compiler_cache_retention import maintain_cache\n"
    "        protected_cache_paths = []\n"
    "        for result in results:\n"
    "            if result[7]:\n"
    "                protected_cache_paths.append(result[7])\n"
    "        retention_report = maintain_cache(_object_cache_dir(), automatic=True, protected_paths=protected_cache_paths)\n"
    "        retention_reclaimed = int(retention_report.get('reclaimed_bytes', 0) or 0)\n"
    "        retention_failures = int(retention_report.get('quarantine_failures', 0) or 0)\n"
    "        retention_pending = int(retention_report.get('quarantine_pending', 0) or 0)\n"
    "        if retention_reclaimed or retention_failures or retention_pending:\n"
    "            sys.stderr.write('pcc compiler cache retention: reclaimed=' + str(retention_reclaimed) + ' failures=' + str(retention_failures) + ' pending=' + str(retention_pending) + '\\n')\n"
    "except Exception as retention_exc:\n"
    "    retention_message = str(retention_exc).replace('\\n', ' ')[:200]\n"
    "    sys.stderr.write('pcc compiler cache retention skipped: ' + type(retention_exc).__name__ + (': ' + retention_message if retention_message else '') + '\\n')\n"
    "with open(result_path, 'w', encoding='utf-8') as out:\n"
    "    for idx, target_id, obj_path, emit_ms, cc_ms, byte_len, cache_status, cache_path in sorted(results):\n"
    "        out.write(str(idx) + '\\t' + target_id + '\\t' + obj_path + '\\t' + str(emit_ms) + '\\t' + str(cc_ms) + '\\t' + str(byte_len) + '\\t' + cache_status + '\\t' + cache_path + '\\n')\n"
)


_SELF_BACKEND_OBJECT_CACHE_PLAN_CODE = (
    "import hashlib\n"
    "import json\n"
    "import os\n"
    "import shutil\n"
    "import subprocess\n"
    "import sys\n"
    "import time\n"
    "version = sys.argv[1]\n"
    "identity = sys.argv[2]\n"
    "target_id = sys.argv[3]\n"
    "cc = sys.argv[4]\n"
    "cache_dir = sys.argv[5]\n"
    "manifest_path = sys.argv[6]\n"
    "plan_path = sys.argv[7]\n"
    "platform_id = sys.platform + ':' + (os.uname().machine or '')\n"
    "try:\n"
    "    cc_identity = subprocess.check_output([cc, '--version'], stderr=subprocess.STDOUT)\n"
    "except Exception:\n"
    "    cc_identity = b'<unknown-toolchain>'\n"
    "def acquire_lease(path, suffix):\n"
    "    os.makedirs(os.path.dirname(path), exist_ok=True)\n"
    "    eviction = path + '.pcc-evict'\n"
    "    if os.path.exists(eviction):\n"
    "        return ''\n"
    "    lease = path + '.pcc-lease.' + str(os.getpid()) + '.' + suffix\n"
    "    try:\n"
    "        fd = os.open(lease, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)\n"
    "        with os.fdopen(fd, 'w', encoding='utf-8') as stream:\n"
    "            json.dump({'pid': os.getpid(), 'created_ns': time.time_ns()}, stream, sort_keys=True, separators=(',', ':'))\n"
    "            stream.write('\\n')\n"
    "        if os.path.exists(eviction):\n"
    "            os.unlink(lease)\n"
    "            return ''\n"
    "        return lease\n"
    "    except OSError:\n"
    "        return ''\n"
    "def touch_entry(path, suffix):\n"
    "    if not os.path.exists(path):\n"
    "        return\n"
    "    marker = path + '.pcc-last-used'\n"
    "    temporary = marker + '.tmp.' + str(os.getpid()) + '.' + suffix\n"
    "    try:\n"
    "        with open(temporary, 'w', encoding='ascii') as stream:\n"
    "            stream.write(str(time.time_ns()) + '\\n')\n"
    "        os.replace(temporary, marker)\n"
    "        if not os.path.exists(path):\n"
    "            os.unlink(marker)\n"
    "    except OSError:\n"
    "        try:\n"
    "            os.unlink(temporary)\n"
    "        except OSError:\n"
    "            pass\n"
    "rows = []\n"
    "with open(manifest_path, 'r', encoding='utf-8') as f:\n"
    "    manifest_lines = f.read().splitlines()\n"
    "for line in manifest_lines:\n"
    "    parts = line.split('\\t')\n"
    "    if len(parts) != 4:\n"
    "        raise RuntimeError('invalid self-backend object-cache manifest')\n"
    "    index_text, ir_path, result_path, obj_path = parts\n"
    "    h = hashlib.sha256()\n"
    "    for value in (version, identity, platform_id, target_id, cc):\n"
    "        h.update(value.encode('utf-8'))\n"
    "        h.update(b'\\0')\n"
    "    h.update(cc_identity)\n"
    "    h.update(b'\\0')\n"
    "    with open(ir_path, 'rb') as ir_file:\n"
    "        while True:\n"
    "            block = ir_file.read(1024 * 1024)\n"
    "            if not block:\n"
    "                break\n"
    "            h.update(block)\n"
    "    digest = h.hexdigest()\n"
    "    if obj_path.endswith('.s'):\n"
    "        artifact_suffix = '.s'\n"
    "    elif obj_path.endswith('.o'):\n"
    "        artifact_suffix = '.o'\n"
    "    else:\n"
    "        raise RuntimeError('unknown self-backend cache artifact kind')\n"
    "    cache_path = os.path.join(cache_dir, digest[:2], digest + artifact_suffix)\n"
    "    checksum_path = cache_path + '.sha256'\n"
    "    status = 'miss'\n"
    "    cache_valid = False\n"
    "    lease_path = ''\n"
    "    if os.path.isfile(cache_path) and os.path.isfile(checksum_path):\n"
    "        lease_path = acquire_lease(cache_path, index_text)\n"
    "    if lease_path:\n"
    "        try:\n"
    "            if os.path.getsize(cache_path) > 0:\n"
    "                with open(checksum_path, 'r', encoding='utf-8') as checksum_file:\n"
    "                    expected_checksum = checksum_file.read().strip()\n"
    "                object_hash = hashlib.sha256()\n"
    "                with open(cache_path, 'rb') as cache_file:\n"
    "                    while True:\n"
    "                        block = cache_file.read(1024 * 1024)\n"
    "                        if not block:\n"
    "                            break\n"
    "                        object_hash.update(block)\n"
    "                cache_valid = len(expected_checksum) == 64 and object_hash.hexdigest() == expected_checksum\n"
    "            if cache_valid:\n"
    "                shutil.copyfile(cache_path, obj_path)\n"
    "                with open(result_path, 'w', encoding='utf-8') as result_file:\n"
    "                    result_file.write(target_id + '\\n')\n"
    "                    result_file.write(obj_path + '\\n')\n"
    "                    result_file.write('hit\\n')\n"
    "                touch_entry(cache_path, index_text)\n"
    "                status = 'hit'\n"
    "        except OSError:\n"
    "            status = 'miss'\n"
    "        finally:\n"
    "            try:\n"
    "                os.unlink(lease_path)\n"
    "            except OSError:\n"
    "                pass\n"
    "    rows.append(index_text + '\\t' + cache_path + '\\t' + status)\n"
    "with open(plan_path, 'w', encoding='utf-8') as f:\n"
    "    f.write('\\n'.join(rows))\n"
    "    if rows:\n"
    "        f.write('\\n')\n"
)


_SELF_BACKEND_OBJECT_CACHE_PUBLISH_CODE = (
    "import hashlib\n"
    "import json\n"
    "import os\n"
    "import shutil\n"
    "import sys\n"
    "import time\n"
    "manifest_path = sys.argv[1]\n"
    "with open(manifest_path, 'r', encoding='utf-8') as f:\n"
    "    rows = f.read().splitlines()\n"
    "for index, row in enumerate(rows):\n"
    "    parts = row.split('\\t')\n"
    "    if len(parts) != 2:\n"
    "        raise RuntimeError('invalid self-backend object-cache publish manifest')\n"
    "    cache_path, obj_path = parts\n"
    "    os.makedirs(os.path.dirname(cache_path), exist_ok=True)\n"
    "    tmp_path = cache_path + '.' + str(os.getpid()) + '.' + str(index) + '.tmp'\n"
    "    checksum_path = cache_path + '.sha256'\n"
    "    checksum_tmp_path = tmp_path + '.sha256'\n"
    "    lease_path = cache_path + '.pcc-lease.' + str(os.getpid()) + '.' + str(index)\n"
    "    eviction_path = cache_path + '.pcc-evict'\n"
    "    if os.path.exists(eviction_path):\n"
    "        continue\n"
    "    try:\n"
    "        lease_fd = os.open(lease_path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)\n"
    "        with os.fdopen(lease_fd, 'w', encoding='utf-8') as lease_file:\n"
    "            json.dump({'pid': os.getpid(), 'created_ns': time.time_ns()}, lease_file, sort_keys=True, separators=(',', ':'))\n"
    "            lease_file.write('\\n')\n"
    "    except OSError:\n"
    "        continue\n"
    "    if os.path.exists(eviction_path):\n"
    "        try:\n"
    "            os.unlink(lease_path)\n"
    "        except OSError:\n"
    "            pass\n"
    "        continue\n"
    "    try:\n"
    "        shutil.copyfile(obj_path, tmp_path)\n"
    "        object_hash = hashlib.sha256()\n"
    "        with open(tmp_path, 'rb') as object_file:\n"
    "            while True:\n"
    "                block = object_file.read(1024 * 1024)\n"
    "                if not block:\n"
    "                    break\n"
    "                object_hash.update(block)\n"
    "        with open(checksum_tmp_path, 'w', encoding='utf-8') as checksum_file:\n"
    "            checksum_file.write(object_hash.hexdigest() + '\\n')\n"
    "        os.replace(tmp_path, cache_path)\n"
    "        os.replace(checksum_tmp_path, checksum_path)\n"
    "        marker_path = cache_path + '.pcc-last-used'\n"
    "        marker_tmp = marker_path + '.tmp.' + str(os.getpid()) + '.' + str(index)\n"
    "        try:\n"
    "            with open(marker_tmp, 'w', encoding='ascii') as marker_file:\n"
    "                marker_file.write(str(time.time_ns()) + '\\n')\n"
    "            os.replace(marker_tmp, marker_path)\n"
    "            if not os.path.exists(cache_path):\n"
    "                os.unlink(marker_path)\n"
    "        except OSError:\n"
    "            pass\n"
    "    finally:\n"
    "        for leftover_path in (tmp_path, checksum_tmp_path, lease_path, cache_path + '.pcc-last-used.tmp.' + str(os.getpid()) + '.' + str(index)):\n"
    "            try:\n"
    "                os.unlink(leftover_path)\n"
    "            except OSError:\n"
    "                pass\n"
)
