"""Static field-order contract for ``pcc.py_frontend.py_ast`` nodes."""

PY_AST_FIELD_NAME_OVERRIDES = {
    "SourceSpan": ("file", "line", "col", "end_line", "end_col"),
    "Type": ("name",),
    "IntType": ("name", "width", "signed"),
    "FloatType": ("name", "width"),
    "ComplexType": ("name",),
    "BoolType": ("name",),
    "NoneType": ("name",),
    "StrType": ("name",),
    "BytesType": ("name",),
    "ByteArrayType": ("name",),
    "MemoryViewType": ("name",),
    "ListType": ("name", "elem"),
    "SetType": ("name", "elem"),
    "ValueArrayType": ("name", "elem", "length"),
    "DictType": ("name", "key", "value"),
    "TupleType": ("name", "elems"),
    "FuncType": ("name", "params", "ret"),
    "ClassType": ("name", "module", "fields", "bases", "properties", "valueclass"),
    "ValueClassType": (
        "name",
        "module",
        "fields",
        "bases",
        "properties",
        "valueclass",
        "flattened",
        "nullable_fields",
    ),
    "DynType": ("name",),
    "Expr": ("span", "ty"),
    "IntLit": ("span", "ty", "value"),
    "FloatLit": ("span", "ty", "value"),
    "ComplexLit": ("span", "ty", "real", "imag"),
    "BoolLit": ("span", "ty", "value"),
    "NoneLit": ("span", "ty"),
    "StrLit": ("span", "ty", "value"),
    "BytesLit": ("span", "ty", "value"),
    "Name": ("span", "ty", "ident"),
    "BinOp": ("span", "ty", "op", "lhs", "rhs"),
    "UnaryOp": ("span", "ty", "op", "operand"),
    "Compare": ("span", "ty", "op", "lhs", "rhs"),
    "BoolExpr": ("span", "ty", "op", "left", "right"),
    "Call": ("span", "ty", "func", "args", "kwargs", "operand_order"),
    "Attr": ("span", "ty", "obj", "name"),
    "Subscript": ("span", "ty", "obj", "idx"),
    "Slice": ("span", "ty", "lo", "hi", "step"),
    "ListExpr": ("span", "ty", "elems"),
    "DictExpr": ("span", "ty", "pairs"),
    "TupleExpr": ("span", "ty", "elems"),
    "IfExpr": ("span", "ty", "cond", "then_e", "else_e"),
    "Lambda": ("span", "ty", "params", "body"),
    "Stmt": ("span",),
    "Assign": ("span", "targets", "value", "annotation"),
    "AugAssign": ("span", "target", "op", "value"),
    "ExprStmt": ("span", "expr"),
    "If": ("span", "cond", "body", "else_body"),
    "While": ("span", "cond", "body", "else_body"),
    "For": ("span", "target", "iter", "body", "else_body", "is_async"),
    "Return": ("span", "value"),
    "Pass": ("span",),
    "Break": ("span",),
    "Continue": ("span",),
    "Raise": ("span", "exc", "cause"),
    "Try": ("span", "body", "handlers", "else_body", "finally_body"),
    "ExceptHandler": ("exc_type", "name", "body", "span"),
    "With": ("span", "items", "body", "is_async"),
    "Import": ("span", "names"),
    "ImportFrom": ("span", "module", "names", "level"),
    "Global": ("span", "names"),
    "Nonlocal": ("span", "names"),
    "Delete": ("span", "targets"),
    "Arg": ("name", "annotation", "default", "kind", "has_default"),
    "FuncDef": (
        "span",
        "name",
        "args",
        "return_ty",
        "body",
        "decorators",
        "is_method",
        "is_async",
    ),
    "ClassDef": ("span", "name", "bases", "keywords", "body", "decorators"),
    "Module": ("name", "body", "docstring"),
}
